# This file was auto-generated by Fern from our API Definition.

import typing

import httpx
from .http_client import AsyncHttpClient, HttpClient
from .logging import LogConfig, Logger


class BaseClientWrapper:
    def __init__(
        self,
        *,
        api_version: typing.Optional[str] = None,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        base_url: str,
        timeout: typing.Optional[float] = None,
        max_retries: int = 2,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
        api_revision: typing.Optional[str] = None,
    ):
        self._api_version = api_version
        self.api_key = api_key
        self._headers = headers
        self._base_url = base_url
        self._timeout = timeout
        self._max_retries = max_retries
        self._logging = logging
        self._api_revision = api_revision

    def get_headers(self) -> typing.Dict[str, str]:
        import platform

        headers: typing.Dict[str, str] = {
            "X-Fern-Language": "Python",
            "X-Fern-Runtime": f"python/{platform.python_version()}",
            "X-Fern-Platform": f"{platform.system().lower()}/{platform.release()}",
            "X-Fern-SDK-Name": "gemini_next_gen_api",
            "X-Fern-SDK-Version": "0.0.49",
            **(self.get_custom_headers() or {}),
        }
        headers["x-goog-api-key"] = self.api_key
        headers["Api-Revision"] = self._api_revision if self._api_revision is not None else "2026-05-20"
        return headers

    def get_custom_headers(self) -> typing.Optional[typing.Dict[str, str]]:
        return self._headers

    def get_base_url(self) -> str:
        return self._base_url

    def get_timeout(self) -> typing.Optional[float]:
        return self._timeout

    def get_max_retries(self) -> int:
        return self._max_retries


class SyncClientWrapper(BaseClientWrapper):
    def __init__(
        self,
        *,
        api_version: typing.Optional[str] = None,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        base_url: str,
        timeout: typing.Optional[float] = None,
        max_retries: int = 2,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
        api_revision: typing.Optional[str] = None,
        httpx_client: httpx.Client,
    ):
        super().__init__(
            api_version=api_version,
            api_key=api_key,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
            max_retries=max_retries,
            logging=logging,
            api_revision=api_revision,
        )
        self.httpx_client = HttpClient(
            httpx_client=httpx_client,
            base_headers=self.get_headers,
            base_timeout=self.get_timeout,
            base_url=self.get_base_url,
            base_max_retries=self.get_max_retries(),
            logging_config=self._logging,
        )


class AsyncClientWrapper(BaseClientWrapper):
    def __init__(
        self,
        *,
        api_version: typing.Optional[str] = None,
        api_key: str,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        base_url: str,
        timeout: typing.Optional[float] = None,
        max_retries: int = 2,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
        api_revision: typing.Optional[str] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        httpx_client: httpx.AsyncClient,
    ):
        super().__init__(
            api_version=api_version,
            api_key=api_key,
            headers=headers,
            base_url=base_url,
            timeout=timeout,
            max_retries=max_retries,
            logging=logging,
            api_revision=api_revision,
        )
        self._async_token = async_token
        self.httpx_client = AsyncHttpClient(
            httpx_client=httpx_client,
            base_headers=self.get_headers,
            base_timeout=self.get_timeout,
            base_url=self.get_base_url,
            base_max_retries=self.get_max_retries(),
            async_base_headers=self.async_get_headers,
            logging_config=self._logging,
        )

    async def async_get_headers(self) -> typing.Dict[str, str]:
        headers = self.get_headers()
        if self._async_token is not None:
            token = await self._async_token()
            headers["Authorization"] = f"Bearer {token}"
        return headers
