# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.interaction import Interaction
from ..types.interaction_sse_event import InteractionSseEvent
from .raw_client import AsyncRawFernInteractionsClient, RawFernInteractionsClient
from .types.create_fern_interactions_request import CreateFernInteractionsRequest
from .types.create_fern_interactions_stream_request import CreateFernInteractionsStreamRequest

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FernInteractionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFernInteractionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFernInteractionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFernInteractionsClient
        """
        return self._raw_client

    def create_stream(
        self, *, request: CreateFernInteractionsStreamRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[InteractionSseEvent]:
        """
        Creates a new interaction.

        Parameters
        ----------
        request : CreateFernInteractionsStreamRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[InteractionSseEvent]


        Examples
        --------
        from google.genai._fern_interactions import (
            CreateModelInteractionParams,
            GeminiNextGenAPIClient,
            TextContent,
        )

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        response = client.fern_interactions.create_stream(
            request=CreateModelInteractionParams(
                model="gemini-2.5-computer-use-preview-10-2025",
                input=TextContent(
                    text="text",
                    type="text",
                ),
            ),
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.create_stream(request=request, request_options=request_options) as r:
            yield from r.data

    def create(
        self, *, request: CreateFernInteractionsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> Interaction:
        """
        Creates a new interaction.

        Parameters
        ----------
        request : CreateFernInteractionsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Interaction


        Examples
        --------
        from google.genai._fern_interactions import (
            CreateModelInteractionParams,
            GeminiNextGenAPIClient,
            TextContent,
        )

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_interactions.create(
            request=CreateModelInteractionParams(
                model="gemini-2.5-computer-use-preview-10-2025",
                input=TextContent(
                    text="text",
                    type="text",
                ),
            ),
        )
        """
        _response = self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    def get_stream(
        self,
        id: str,
        *,
        stream: typing.Optional[bool] = None,
        last_event_id: typing.Optional[str] = None,
        include_input: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[InteractionSseEvent]:
        """
        Retrieves the full details of a single interaction based on its `Interaction.id`.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to retrieve.

        stream : typing.Optional[bool]
            If set to true, the generated content will be streamed incrementally.

        last_event_id : typing.Optional[str]
            Optional. If set, resumes the interaction stream from the next chunk after the event marked by the event id. Can only be used if `stream` is true.

        include_input : typing.Optional[bool]
            If set to true, includes the input in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[InteractionSseEvent]


        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        response = client.fern_interactions.get_stream(
            id="id",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.get_stream(
            id, stream=stream, last_event_id=last_event_id, include_input=include_input, request_options=request_options
        ) as r:
            yield from r.data

    def get(
        self,
        id: str,
        *,
        stream: typing.Optional[bool] = None,
        last_event_id: typing.Optional[str] = None,
        include_input: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Interaction:
        """
        Retrieves the full details of a single interaction based on its `Interaction.id`.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to retrieve.

        stream : typing.Optional[bool]
            If set to true, the generated content will be streamed incrementally.

        last_event_id : typing.Optional[str]
            Optional. If set, resumes the interaction stream from the next chunk after the event marked by the event id. Can only be used if `stream` is true.

        include_input : typing.Optional[bool]
            If set to true, includes the input in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Interaction


        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_interactions.get(
            id="id",
        )
        """
        _response = self._raw_client.get(
            id, stream=stream, last_event_id=last_event_id, include_input=include_input, request_options=request_options
        )
        return _response.data

    def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Deletes the interaction by id.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful deletion of the interaction.

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_interactions.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def cancel(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Interaction:
        """
        Cancels an interaction by id. This only applies to background interactions that are still running.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to cancel.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Interaction
            Successful cancellation of the interaction.

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_interactions.cancel(
            id="id",
        )
        """
        _response = self._raw_client.cancel(id, request_options=request_options)
        return _response.data


class AsyncFernInteractionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFernInteractionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFernInteractionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFernInteractionsClient
        """
        return self._raw_client

    async def create_stream(
        self, *, request: CreateFernInteractionsStreamRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[InteractionSseEvent]:
        """
        Creates a new interaction.

        Parameters
        ----------
        request : CreateFernInteractionsStreamRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[InteractionSseEvent]


        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import (
            AsyncGeminiNextGenAPIClient,
            CreateModelInteractionParams,
            TextContent,
        )

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.fern_interactions.create_stream(
                request=CreateModelInteractionParams(
                    model="gemini-2.5-computer-use-preview-10-2025",
                    input=TextContent(
                        text="text",
                        type="text",
                    ),
                ),
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.create_stream(request=request, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def create(
        self, *, request: CreateFernInteractionsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> Interaction:
        """
        Creates a new interaction.

        Parameters
        ----------
        request : CreateFernInteractionsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Interaction


        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import (
            AsyncGeminiNextGenAPIClient,
            CreateModelInteractionParams,
            TextContent,
        )

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_interactions.create(
                request=CreateModelInteractionParams(
                    model="gemini-2.5-computer-use-preview-10-2025",
                    input=TextContent(
                        text="text",
                        type="text",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    async def get_stream(
        self,
        id: str,
        *,
        stream: typing.Optional[bool] = None,
        last_event_id: typing.Optional[str] = None,
        include_input: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[InteractionSseEvent]:
        """
        Retrieves the full details of a single interaction based on its `Interaction.id`.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to retrieve.

        stream : typing.Optional[bool]
            If set to true, the generated content will be streamed incrementally.

        last_event_id : typing.Optional[str]
            Optional. If set, resumes the interaction stream from the next chunk after the event marked by the event id. Can only be used if `stream` is true.

        include_input : typing.Optional[bool]
            If set to true, includes the input in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[InteractionSseEvent]


        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            response = await client.fern_interactions.get_stream(
                id="id",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.get_stream(
            id, stream=stream, last_event_id=last_event_id, include_input=include_input, request_options=request_options
        ) as r:
            async for _chunk in r.data:
                yield _chunk

    async def get(
        self,
        id: str,
        *,
        stream: typing.Optional[bool] = None,
        last_event_id: typing.Optional[str] = None,
        include_input: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Interaction:
        """
        Retrieves the full details of a single interaction based on its `Interaction.id`.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to retrieve.

        stream : typing.Optional[bool]
            If set to true, the generated content will be streamed incrementally.

        last_event_id : typing.Optional[str]
            Optional. If set, resumes the interaction stream from the next chunk after the event marked by the event id. Can only be used if `stream` is true.

        include_input : typing.Optional[bool]
            If set to true, includes the input in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Interaction


        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_interactions.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(
            id, stream=stream, last_event_id=last_event_id, include_input=include_input, request_options=request_options
        )
        return _response.data

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Deletes the interaction by id.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful deletion of the interaction.

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_interactions.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def cancel(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Interaction:
        """
        Cancels an interaction by id. This only applies to background interactions that are still running.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to cancel.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Interaction
            Successful cancellation of the interaction.

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_interactions.cancel(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(id, request_options=request_options)
        return _response.data
