# This file was auto-generated by Fern from our API Definition.

import contextlib
import typing
from json.decoder import JSONDecodeError
from logging import error, warning

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.http_sse._api import EventSource
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as, parse_sse_obj
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.interaction import Interaction
from ..types.interaction_sse_event import InteractionSseEvent
from .types.create_fern_interactions_request import CreateFernInteractionsRequest
from .types.create_fern_interactions_stream_request import CreateFernInteractionsStreamRequest
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawFernInteractionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    @contextlib.contextmanager
    def create_stream(
        self, *, request: CreateFernInteractionsStreamRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[HttpResponse[typing.Iterator[InteractionSseEvent]]]:
        """
        Creates a new interaction.

        Parameters
        ----------
        request : CreateFernInteractionsStreamRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[HttpResponse[typing.Iterator[InteractionSseEvent]]]

        """
        with self._client_wrapper.httpx_client.stream(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=CreateFernInteractionsStreamRequest, direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        ) as _response:

            def _stream() -> HttpResponse[typing.Iterator[InteractionSseEvent]]:
                try:
                    if 200 <= _response.status_code < 300:

                        def _iter():
                            _event_source = EventSource(_response)
                            for _sse in _event_source.iter_sse():
                                if _sse.data == "[DONE]":
                                    return
                                try:
                                    yield typing.cast(
                                        InteractionSseEvent,
                                        parse_sse_obj(
                                            sse=_sse,
                                            type_=InteractionSseEvent,  # type: ignore
                                        ),
                                    )
                                except JSONDecodeError as e:
                                    warning(f"Skipping SSE event with invalid JSON: {e}, sse: {_sse!r}")
                                except (TypeError, ValueError, KeyError, AttributeError) as e:
                                    warning(
                                        f"Skipping SSE event due to model construction error: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                                except Exception as e:
                                    error(
                                        f"Unexpected error processing SSE event: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                            return

                        return HttpResponse(response=_response, data=_iter())
                    _response.read()
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield _stream()

    def create(
        self, *, request: CreateFernInteractionsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[Interaction]:
        """
        Creates a new interaction.

        Parameters
        ----------
        request : CreateFernInteractionsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Interaction]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=CreateFernInteractionsRequest, direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Interaction,
                    parse_obj_as(
                        type_=Interaction,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.contextmanager
    def get_stream(
        self,
        id: str,
        *,
        stream: typing.Optional[bool] = None,
        last_event_id: typing.Optional[str] = None,
        include_input: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[HttpResponse[typing.Iterator[InteractionSseEvent]]]:
        """
        Retrieves the full details of a single interaction based on its `Interaction.id`.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to retrieve.

        stream : typing.Optional[bool]
            If set to true, the generated content will be streamed incrementally.

        last_event_id : typing.Optional[str]
            Optional. If set, resumes the interaction stream from the next chunk after the event marked by the event id. Can only be used if `stream` is true.

        include_input : typing.Optional[bool]
            If set to true, includes the input in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[HttpResponse[typing.Iterator[InteractionSseEvent]]]

        """
        with self._client_wrapper.httpx_client.stream(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions/{encode_path_param(id)}",
            method="GET",
            params={
                "stream": stream,
                "last_event_id": last_event_id,
                "include_input": include_input,
            },
            request_options=request_options,
        ) as _response:

            def _stream() -> HttpResponse[typing.Iterator[InteractionSseEvent]]:
                try:
                    if 200 <= _response.status_code < 300:

                        def _iter():
                            _event_source = EventSource(_response)
                            for _sse in _event_source.iter_sse():
                                if _sse.data == "[DONE]":
                                    return
                                try:
                                    yield typing.cast(
                                        InteractionSseEvent,
                                        parse_sse_obj(
                                            sse=_sse,
                                            type_=InteractionSseEvent,  # type: ignore
                                        ),
                                    )
                                except JSONDecodeError as e:
                                    warning(f"Skipping SSE event with invalid JSON: {e}, sse: {_sse!r}")
                                except (TypeError, ValueError, KeyError, AttributeError) as e:
                                    warning(
                                        f"Skipping SSE event due to model construction error: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                                except Exception as e:
                                    error(
                                        f"Unexpected error processing SSE event: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                            return

                        return HttpResponse(response=_response, data=_iter())
                    _response.read()
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield _stream()

    def get(
        self,
        id: str,
        *,
        stream: typing.Optional[bool] = None,
        last_event_id: typing.Optional[str] = None,
        include_input: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Interaction]:
        """
        Retrieves the full details of a single interaction based on its `Interaction.id`.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to retrieve.

        stream : typing.Optional[bool]
            If set to true, the generated content will be streamed incrementally.

        last_event_id : typing.Optional[str]
            Optional. If set, resumes the interaction stream from the next chunk after the event marked by the event id. Can only be used if `stream` is true.

        include_input : typing.Optional[bool]
            If set to true, includes the input in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Interaction]

        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions/{encode_path_param(id)}",
            method="GET",
            params={
                "stream": stream,
                "last_event_id": last_event_id,
                "include_input": include_input,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Interaction,
                    parse_obj_as(
                        type_=Interaction,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Dict[str, typing.Any]]:
        """
        Deletes the interaction by id.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Dict[str, typing.Any]]
            Successful deletion of the interaction.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, typing.Any],
                    parse_obj_as(
                        type_=typing.Dict[str, typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def cancel(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[Interaction]:
        """
        Cancels an interaction by id. This only applies to background interactions that are still running.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to cancel.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Interaction]
            Successful cancellation of the interaction.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions/{encode_path_param(id)}/cancel",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Interaction,
                    parse_obj_as(
                        type_=Interaction,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawFernInteractionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    @contextlib.asynccontextmanager
    async def create_stream(
        self, *, request: CreateFernInteractionsStreamRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[InteractionSseEvent]]]:
        """
        Creates a new interaction.

        Parameters
        ----------
        request : CreateFernInteractionsStreamRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[InteractionSseEvent]]]

        """
        async with self._client_wrapper.httpx_client.stream(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=CreateFernInteractionsStreamRequest, direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        ) as _response:

            async def _stream() -> AsyncHttpResponse[typing.AsyncIterator[InteractionSseEvent]]:
                try:
                    if 200 <= _response.status_code < 300:

                        async def _iter():
                            _event_source = EventSource(_response)
                            async for _sse in _event_source.aiter_sse():
                                if _sse.data == "[DONE]":
                                    return
                                try:
                                    yield typing.cast(
                                        InteractionSseEvent,
                                        parse_sse_obj(
                                            sse=_sse,
                                            type_=InteractionSseEvent,  # type: ignore
                                        ),
                                    )
                                except JSONDecodeError as e:
                                    warning(f"Skipping SSE event with invalid JSON: {e}, sse: {_sse!r}")
                                except (TypeError, ValueError, KeyError, AttributeError) as e:
                                    warning(
                                        f"Skipping SSE event due to model construction error: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                                except Exception as e:
                                    error(
                                        f"Unexpected error processing SSE event: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                            return

                        return AsyncHttpResponse(response=_response, data=_iter())
                    await _response.aread()
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield await _stream()

    async def create(
        self, *, request: CreateFernInteractionsRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Interaction]:
        """
        Creates a new interaction.

        Parameters
        ----------
        request : CreateFernInteractionsRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Interaction]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions",
            method="POST",
            json=convert_and_respect_annotation_metadata(
                object_=request, annotation=CreateFernInteractionsRequest, direction="write"
            ),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Interaction,
                    parse_obj_as(
                        type_=Interaction,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.asynccontextmanager
    async def get_stream(
        self,
        id: str,
        *,
        stream: typing.Optional[bool] = None,
        last_event_id: typing.Optional[str] = None,
        include_input: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[InteractionSseEvent]]]:
        """
        Retrieves the full details of a single interaction based on its `Interaction.id`.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to retrieve.

        stream : typing.Optional[bool]
            If set to true, the generated content will be streamed incrementally.

        last_event_id : typing.Optional[str]
            Optional. If set, resumes the interaction stream from the next chunk after the event marked by the event id. Can only be used if `stream` is true.

        include_input : typing.Optional[bool]
            If set to true, includes the input in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[InteractionSseEvent]]]

        """
        async with self._client_wrapper.httpx_client.stream(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions/{encode_path_param(id)}",
            method="GET",
            params={
                "stream": stream,
                "last_event_id": last_event_id,
                "include_input": include_input,
            },
            request_options=request_options,
        ) as _response:

            async def _stream() -> AsyncHttpResponse[typing.AsyncIterator[InteractionSseEvent]]:
                try:
                    if 200 <= _response.status_code < 300:

                        async def _iter():
                            _event_source = EventSource(_response)
                            async for _sse in _event_source.aiter_sse():
                                if _sse.data == "[DONE]":
                                    return
                                try:
                                    yield typing.cast(
                                        InteractionSseEvent,
                                        parse_sse_obj(
                                            sse=_sse,
                                            type_=InteractionSseEvent,  # type: ignore
                                        ),
                                    )
                                except JSONDecodeError as e:
                                    warning(f"Skipping SSE event with invalid JSON: {e}, sse: {_sse!r}")
                                except (TypeError, ValueError, KeyError, AttributeError) as e:
                                    warning(
                                        f"Skipping SSE event due to model construction error: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                                except Exception as e:
                                    error(
                                        f"Unexpected error processing SSE event: {type(e).__name__}: {e}, sse: {_sse!r}"
                                    )
                            return

                        return AsyncHttpResponse(response=_response, data=_iter())
                    await _response.aread()
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                except ValidationError as e:
                    raise ParsingError(
                        status_code=_response.status_code,
                        headers=dict(_response.headers),
                        body=_response.json(),
                        cause=e,
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield await _stream()

    async def get(
        self,
        id: str,
        *,
        stream: typing.Optional[bool] = None,
        last_event_id: typing.Optional[str] = None,
        include_input: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Interaction]:
        """
        Retrieves the full details of a single interaction based on its `Interaction.id`.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to retrieve.

        stream : typing.Optional[bool]
            If set to true, the generated content will be streamed incrementally.

        last_event_id : typing.Optional[str]
            Optional. If set, resumes the interaction stream from the next chunk after the event marked by the event id. Can only be used if `stream` is true.

        include_input : typing.Optional[bool]
            If set to true, includes the input in the response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Interaction]

        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions/{encode_path_param(id)}",
            method="GET",
            params={
                "stream": stream,
                "last_event_id": last_event_id,
                "include_input": include_input,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Interaction,
                    parse_obj_as(
                        type_=Interaction,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Dict[str, typing.Any]]:
        """
        Deletes the interaction by id.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Dict[str, typing.Any]]
            Successful deletion of the interaction.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, typing.Any],
                    parse_obj_as(
                        type_=typing.Dict[str, typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def cancel(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Interaction]:
        """
        Cancels an interaction by id. This only applies to background interactions that are still running.

        Parameters
        ----------
        id : str
            The unique identifier of the interaction to cancel.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Interaction]
            Successful cancellation of the interaction.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/interactions/{encode_path_param(id)}/cancel",
            method="POST",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Interaction,
                    parse_obj_as(
                        type_=Interaction,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
