# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.agent import Agent
from ..types.agent_base_environment import AgentBaseEnvironment
from ..types.agent_tool import AgentTool
from ..types.empty import Empty
from ..types.list_agents_response import ListAgentsResponse
from .raw_client import AsyncRawFernAgentsClient, RawFernAgentsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FernAgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFernAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFernAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFernAgentsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        parent: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentsResponse:
        """
        Lists all Agents.

        Parameters
        ----------
        parent : typing.Optional[str]

        page_size : typing.Optional[int]

        page_token : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentsResponse
            Successful operation

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_agents.list()
        """
        _response = self._raw_client.list(
            parent=parent, page_size=page_size, page_token=page_token, request_options=request_options
        )
        return _response.data

    def create(
        self,
        *,
        base_agent: typing.Optional[str] = OMIT,
        base_environment: typing.Optional[AgentBaseEnvironment] = OMIT,
        description: typing.Optional[str] = OMIT,
        id: typing.Optional[str] = OMIT,
        system_instruction: typing.Optional[str] = OMIT,
        tools: typing.Optional[typing.Sequence[AgentTool]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Agent:
        """
        Creates a new Agent (Typed version for SDK).

        Parameters
        ----------
        base_agent : typing.Optional[str]
            The base agent to extend.

        base_environment : typing.Optional[AgentBaseEnvironment]
            The environment configuration for the agent.

        description : typing.Optional[str]
            Agent description for developers to quickly read and understand.

        id : typing.Optional[str]
            The unique identifier for the agent.

        system_instruction : typing.Optional[str]
            System instruction for the agent.

        tools : typing.Optional[typing.Sequence[AgentTool]]
            The tools available to the agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Agent
            Successful operation

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_agents.create()
        """
        _response = self._raw_client.create(
            base_agent=base_agent,
            base_environment=base_environment,
            description=description,
            id=id,
            system_instruction=system_instruction,
            tools=tools,
            request_options=request_options,
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Agent:
        """
        Gets a specific Agent.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Agent
            Successful operation

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_agents.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Empty:
        """
        Deletes an Agent.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Empty
            Successful operation

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_agents.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data


class AsyncFernAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFernAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFernAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFernAgentsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        parent: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentsResponse:
        """
        Lists all Agents.

        Parameters
        ----------
        parent : typing.Optional[str]

        page_size : typing.Optional[int]

        page_token : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentsResponse
            Successful operation

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_agents.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            parent=parent, page_size=page_size, page_token=page_token, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        *,
        base_agent: typing.Optional[str] = OMIT,
        base_environment: typing.Optional[AgentBaseEnvironment] = OMIT,
        description: typing.Optional[str] = OMIT,
        id: typing.Optional[str] = OMIT,
        system_instruction: typing.Optional[str] = OMIT,
        tools: typing.Optional[typing.Sequence[AgentTool]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Agent:
        """
        Creates a new Agent (Typed version for SDK).

        Parameters
        ----------
        base_agent : typing.Optional[str]
            The base agent to extend.

        base_environment : typing.Optional[AgentBaseEnvironment]
            The environment configuration for the agent.

        description : typing.Optional[str]
            Agent description for developers to quickly read and understand.

        id : typing.Optional[str]
            The unique identifier for the agent.

        system_instruction : typing.Optional[str]
            System instruction for the agent.

        tools : typing.Optional[typing.Sequence[AgentTool]]
            The tools available to the agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Agent
            Successful operation

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_agents.create()


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            base_agent=base_agent,
            base_environment=base_environment,
            description=description,
            id=id,
            system_instruction=system_instruction,
            tools=tools,
            request_options=request_options,
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Agent:
        """
        Gets a specific Agent.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Agent
            Successful operation

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_agents.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Empty:
        """
        Deletes an Agent.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Empty
            Successful operation

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_agents.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data
