# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.agent import Agent
from ..types.agent_base_environment import AgentBaseEnvironment
from ..types.agent_tool import AgentTool
from ..types.empty import Empty
from ..types.list_agents_response import ListAgentsResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawFernAgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        parent: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListAgentsResponse]:
        """
        Lists all Agents.

        Parameters
        ----------
        parent : typing.Optional[str]

        page_size : typing.Optional[int]

        page_token : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListAgentsResponse]
            Successful operation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/agents",
            method="GET",
            params={
                "parent": parent,
                "pageSize": page_size,
                "pageToken": page_token,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListAgentsResponse,
                    parse_obj_as(
                        type_=ListAgentsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        base_agent: typing.Optional[str] = OMIT,
        base_environment: typing.Optional[AgentBaseEnvironment] = OMIT,
        description: typing.Optional[str] = OMIT,
        id: typing.Optional[str] = OMIT,
        system_instruction: typing.Optional[str] = OMIT,
        tools: typing.Optional[typing.Sequence[AgentTool]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[Agent]:
        """
        Creates a new Agent (Typed version for SDK).

        Parameters
        ----------
        base_agent : typing.Optional[str]
            The base agent to extend.

        base_environment : typing.Optional[AgentBaseEnvironment]
            The environment configuration for the agent.

        description : typing.Optional[str]
            Agent description for developers to quickly read and understand.

        id : typing.Optional[str]
            The unique identifier for the agent.

        system_instruction : typing.Optional[str]
            System instruction for the agent.

        tools : typing.Optional[typing.Sequence[AgentTool]]
            The tools available to the agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Agent]
            Successful operation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/agents",
            method="POST",
            json={
                "base_agent": base_agent,
                "base_environment": convert_and_respect_annotation_metadata(
                    object_=base_environment, annotation=AgentBaseEnvironment, direction="write"
                ),
                "description": description,
                "id": id,
                "system_instruction": system_instruction,
                "tools": convert_and_respect_annotation_metadata(
                    object_=tools, annotation=typing.Sequence[AgentTool], direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Agent,
                    parse_obj_as(
                        type_=Agent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[Agent]:
        """
        Gets a specific Agent.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Agent]
            Successful operation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/agents/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Agent,
                    parse_obj_as(
                        type_=Agent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[Empty]:
        """
        Deletes an Agent.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Empty]
            Successful operation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/agents/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Empty,
                    parse_obj_as(
                        type_=Empty,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawFernAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        parent: typing.Optional[str] = None,
        page_size: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListAgentsResponse]:
        """
        Lists all Agents.

        Parameters
        ----------
        parent : typing.Optional[str]

        page_size : typing.Optional[int]

        page_token : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListAgentsResponse]
            Successful operation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/agents",
            method="GET",
            params={
                "parent": parent,
                "pageSize": page_size,
                "pageToken": page_token,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListAgentsResponse,
                    parse_obj_as(
                        type_=ListAgentsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        base_agent: typing.Optional[str] = OMIT,
        base_environment: typing.Optional[AgentBaseEnvironment] = OMIT,
        description: typing.Optional[str] = OMIT,
        id: typing.Optional[str] = OMIT,
        system_instruction: typing.Optional[str] = OMIT,
        tools: typing.Optional[typing.Sequence[AgentTool]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[Agent]:
        """
        Creates a new Agent (Typed version for SDK).

        Parameters
        ----------
        base_agent : typing.Optional[str]
            The base agent to extend.

        base_environment : typing.Optional[AgentBaseEnvironment]
            The environment configuration for the agent.

        description : typing.Optional[str]
            Agent description for developers to quickly read and understand.

        id : typing.Optional[str]
            The unique identifier for the agent.

        system_instruction : typing.Optional[str]
            System instruction for the agent.

        tools : typing.Optional[typing.Sequence[AgentTool]]
            The tools available to the agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Agent]
            Successful operation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/agents",
            method="POST",
            json={
                "base_agent": base_agent,
                "base_environment": convert_and_respect_annotation_metadata(
                    object_=base_environment, annotation=AgentBaseEnvironment, direction="write"
                ),
                "description": description,
                "id": id,
                "system_instruction": system_instruction,
                "tools": convert_and_respect_annotation_metadata(
                    object_=tools, annotation=typing.Sequence[AgentTool], direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Agent,
                    parse_obj_as(
                        type_=Agent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Agent]:
        """
        Gets a specific Agent.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Agent]
            Successful operation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/agents/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Agent,
                    parse_obj_as(
                        type_=Agent,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Empty]:
        """
        Deletes an Agent.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Empty]
            Successful operation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/agents/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Empty,
                    parse_obj_as(
                        type_=Empty,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
