# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.empty import Empty
from ..types.list_webhooks_response import ListWebhooksResponse
from ..types.ping_webhook_request import PingWebhookRequest
from ..types.ping_webhook_response import PingWebhookResponse
from ..types.rotate_signing_secret_response import RotateSigningSecretResponse
from ..types.webhook_read import WebhookRead
from ..types.webhook_subscribed_events_item import WebhookSubscribedEventsItem
from .raw_client import AsyncRawFernWebhooksClient, RawFernWebhooksClient
from .types.rotate_signing_secret_request_revocation_behavior import RotateSigningSecretRequestRevocationBehavior
from .types.webhook_update_state import WebhookUpdateState
from .types.webhook_update_subscribed_events_item import WebhookUpdateSubscribedEventsItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FernWebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFernWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFernWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFernWebhooksClient
        """
        return self._raw_client

    def list(
        self,
        *,
        page_size: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhooksResponse:
        """
        Lists all Webhooks.

        Parameters
        ----------
        page_size : typing.Optional[int]
            Optional. The maximum number of webhooks to return. The service may return fewer than
            this value. If unspecified, at most 50 webhooks will be returned.
            The maximum value is 1000.

        page_token : typing.Optional[str]
            Optional. A page token, received from a previous `ListWebhooks` call.
            Provide this to retrieve the subsequent page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponse
            Successful operation

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_webhooks.list()
        """
        _response = self._raw_client.list(page_size=page_size, page_token=page_token, request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        subscribed_events: typing.Sequence[WebhookSubscribedEventsItem],
        uri: str,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookRead:
        """
        Creates a new Webhook.

        Parameters
        ----------
        subscribed_events : typing.Sequence[WebhookSubscribedEventsItem]
            Required. The events that the webhook is subscribed to.
            Available events:
            - batch.succeeded
            - batch.expired
            - batch.failed
            - interaction.requires_action
            - interaction.completed
            - interaction.failed
            - video.generated

        uri : str
            Required. The URI to which webhook events will be sent.

        name : typing.Optional[str]
            Optional. The user-provided name of the webhook.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookRead
            Successful operation

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_webhooks.create(
            subscribed_events=["batch.succeeded"],
            uri="uri",
        )
        """
        _response = self._raw_client.create(
            subscribed_events=subscribed_events, uri=uri, name=name, request_options=request_options
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> WebhookRead:
        """
        Gets a specific Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookRead
            Successful operation

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_webhooks.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Empty:
        """
        Deletes a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to delete.
            Format: `{webhook_id}`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Empty
            Successful operation

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_webhooks.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        update_mask: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        state: typing.Optional[WebhookUpdateState] = OMIT,
        subscribed_events: typing.Optional[typing.Sequence[WebhookUpdateSubscribedEventsItem]] = OMIT,
        uri: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookRead:
        """
        Updates an existing Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to update.

        update_mask : typing.Optional[str]
            Optional. The list of fields to update.

        name : typing.Optional[str]
            Optional. The user-provided name of the webhook.

        state : typing.Optional[WebhookUpdateState]
            Optional. The state of the webhook.

        subscribed_events : typing.Optional[typing.Sequence[WebhookUpdateSubscribedEventsItem]]
            Optional. The events that the webhook is subscribed to.
            Available events:
            - batch.succeeded
            - batch.expired
            - batch.failed
            - interaction.requires_action
            - interaction.completed
            - interaction.failed
            - video.generated

        uri : typing.Optional[str]
            Optional. The URI to which webhook events will be sent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookRead
            Successful operation

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_webhooks.update(
            id="id",
        )
        """
        _response = self._raw_client.update(
            id,
            update_mask=update_mask,
            name=name,
            state=state,
            subscribed_events=subscribed_events,
            uri=uri,
            request_options=request_options,
        )
        return _response.data

    def rotate_signing_secret(
        self,
        id: str,
        *,
        revocation_behavior: typing.Optional[RotateSigningSecretRequestRevocationBehavior] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RotateSigningSecretResponse:
        """
        Generates a new signing secret for a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook for which to generate a signing secret.
            Format: `{webhook_id}`

        revocation_behavior : typing.Optional[RotateSigningSecretRequestRevocationBehavior]
            Optional. The revocation behavior for previous signing secrets.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RotateSigningSecretResponse
            Successful operation

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_webhooks.rotate_signing_secret(
            id="id",
        )
        """
        _response = self._raw_client.rotate_signing_secret(
            id, revocation_behavior=revocation_behavior, request_options=request_options
        )
        return _response.data

    def ping(
        self, id: str, *, request: PingWebhookRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> PingWebhookResponse:
        """
        Sends a ping event to a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to ping.
            Format: `{webhook_id}`

        request : PingWebhookRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PingWebhookResponse
            Successful operation

        Examples
        --------
        from google.genai._fern_interactions import GeminiNextGenAPIClient

        client = GeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )
        client.fern_webhooks.ping(
            id="id",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.ping(id, request=request, request_options=request_options)
        return _response.data


class AsyncFernWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFernWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFernWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFernWebhooksClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        page_size: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhooksResponse:
        """
        Lists all Webhooks.

        Parameters
        ----------
        page_size : typing.Optional[int]
            Optional. The maximum number of webhooks to return. The service may return fewer than
            this value. If unspecified, at most 50 webhooks will be returned.
            The maximum value is 1000.

        page_token : typing.Optional[str]
            Optional. A page token, received from a previous `ListWebhooks` call.
            Provide this to retrieve the subsequent page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponse
            Successful operation

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_webhooks.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            page_size=page_size, page_token=page_token, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        *,
        subscribed_events: typing.Sequence[WebhookSubscribedEventsItem],
        uri: str,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookRead:
        """
        Creates a new Webhook.

        Parameters
        ----------
        subscribed_events : typing.Sequence[WebhookSubscribedEventsItem]
            Required. The events that the webhook is subscribed to.
            Available events:
            - batch.succeeded
            - batch.expired
            - batch.failed
            - interaction.requires_action
            - interaction.completed
            - interaction.failed
            - video.generated

        uri : str
            Required. The URI to which webhook events will be sent.

        name : typing.Optional[str]
            Optional. The user-provided name of the webhook.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookRead
            Successful operation

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_webhooks.create(
                subscribed_events=["batch.succeeded"],
                uri="uri",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            subscribed_events=subscribed_events, uri=uri, name=name, request_options=request_options
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> WebhookRead:
        """
        Gets a specific Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookRead
            Successful operation

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_webhooks.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Empty:
        """
        Deletes a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to delete.
            Format: `{webhook_id}`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Empty
            Successful operation

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_webhooks.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        update_mask: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        state: typing.Optional[WebhookUpdateState] = OMIT,
        subscribed_events: typing.Optional[typing.Sequence[WebhookUpdateSubscribedEventsItem]] = OMIT,
        uri: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookRead:
        """
        Updates an existing Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to update.

        update_mask : typing.Optional[str]
            Optional. The list of fields to update.

        name : typing.Optional[str]
            Optional. The user-provided name of the webhook.

        state : typing.Optional[WebhookUpdateState]
            Optional. The state of the webhook.

        subscribed_events : typing.Optional[typing.Sequence[WebhookUpdateSubscribedEventsItem]]
            Optional. The events that the webhook is subscribed to.
            Available events:
            - batch.succeeded
            - batch.expired
            - batch.failed
            - interaction.requires_action
            - interaction.completed
            - interaction.failed
            - video.generated

        uri : typing.Optional[str]
            Optional. The URI to which webhook events will be sent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookRead
            Successful operation

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_webhooks.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            update_mask=update_mask,
            name=name,
            state=state,
            subscribed_events=subscribed_events,
            uri=uri,
            request_options=request_options,
        )
        return _response.data

    async def rotate_signing_secret(
        self,
        id: str,
        *,
        revocation_behavior: typing.Optional[RotateSigningSecretRequestRevocationBehavior] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RotateSigningSecretResponse:
        """
        Generates a new signing secret for a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook for which to generate a signing secret.
            Format: `{webhook_id}`

        revocation_behavior : typing.Optional[RotateSigningSecretRequestRevocationBehavior]
            Optional. The revocation behavior for previous signing secrets.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RotateSigningSecretResponse
            Successful operation

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_webhooks.rotate_signing_secret(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rotate_signing_secret(
            id, revocation_behavior=revocation_behavior, request_options=request_options
        )
        return _response.data

    async def ping(
        self, id: str, *, request: PingWebhookRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> PingWebhookResponse:
        """
        Sends a ping event to a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to ping.
            Format: `{webhook_id}`

        request : PingWebhookRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PingWebhookResponse
            Successful operation

        Examples
        --------
        import asyncio

        from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

        client = AsyncGeminiNextGenAPIClient(
            "v1beta",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.fern_webhooks.ping(
                id="id",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.ping(id, request=request, request_options=request_options)
        return _response.data
