# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.empty import Empty
from ..types.list_webhooks_response import ListWebhooksResponse
from ..types.ping_webhook_request import PingWebhookRequest
from ..types.ping_webhook_response import PingWebhookResponse
from ..types.rotate_signing_secret_response import RotateSigningSecretResponse
from ..types.webhook_read import WebhookRead
from ..types.webhook_subscribed_events_item import WebhookSubscribedEventsItem
from .types.rotate_signing_secret_request_revocation_behavior import RotateSigningSecretRequestRevocationBehavior
from .types.webhook_update_state import WebhookUpdateState
from .types.webhook_update_subscribed_events_item import WebhookUpdateSubscribedEventsItem
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawFernWebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        page_size: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListWebhooksResponse]:
        """
        Lists all Webhooks.

        Parameters
        ----------
        page_size : typing.Optional[int]
            Optional. The maximum number of webhooks to return. The service may return fewer than
            this value. If unspecified, at most 50 webhooks will be returned.
            The maximum value is 1000.

        page_token : typing.Optional[str]
            Optional. A page token, received from a previous `ListWebhooks` call.
            Provide this to retrieve the subsequent page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListWebhooksResponse]
            Successful operation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks",
            method="GET",
            params={
                "page_size": page_size,
                "page_token": page_token,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListWebhooksResponse,
                    parse_obj_as(
                        type_=ListWebhooksResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        subscribed_events: typing.Sequence[WebhookSubscribedEventsItem],
        uri: str,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WebhookRead]:
        """
        Creates a new Webhook.

        Parameters
        ----------
        subscribed_events : typing.Sequence[WebhookSubscribedEventsItem]
            Required. The events that the webhook is subscribed to.
            Available events:
            - batch.succeeded
            - batch.expired
            - batch.failed
            - interaction.requires_action
            - interaction.completed
            - interaction.failed
            - video.generated

        uri : str
            Required. The URI to which webhook events will be sent.

        name : typing.Optional[str]
            Optional. The user-provided name of the webhook.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WebhookRead]
            Successful operation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks",
            method="POST",
            json={
                "name": name,
                "subscribed_events": convert_and_respect_annotation_metadata(
                    object_=subscribed_events,
                    annotation=typing.Sequence[WebhookSubscribedEventsItem],
                    direction="write",
                ),
                "uri": uri,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookRead,
                    parse_obj_as(
                        type_=WebhookRead,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[WebhookRead]:
        """
        Gets a specific Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WebhookRead]
            Successful operation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookRead,
                    parse_obj_as(
                        type_=WebhookRead,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[Empty]:
        """
        Deletes a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to delete.
            Format: `{webhook_id}`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[Empty]
            Successful operation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Empty,
                    parse_obj_as(
                        type_=Empty,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        id: str,
        *,
        update_mask: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        state: typing.Optional[WebhookUpdateState] = OMIT,
        subscribed_events: typing.Optional[typing.Sequence[WebhookUpdateSubscribedEventsItem]] = OMIT,
        uri: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WebhookRead]:
        """
        Updates an existing Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to update.

        update_mask : typing.Optional[str]
            Optional. The list of fields to update.

        name : typing.Optional[str]
            Optional. The user-provided name of the webhook.

        state : typing.Optional[WebhookUpdateState]
            Optional. The state of the webhook.

        subscribed_events : typing.Optional[typing.Sequence[WebhookUpdateSubscribedEventsItem]]
            Optional. The events that the webhook is subscribed to.
            Available events:
            - batch.succeeded
            - batch.expired
            - batch.failed
            - interaction.requires_action
            - interaction.completed
            - interaction.failed
            - video.generated

        uri : typing.Optional[str]
            Optional. The URI to which webhook events will be sent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WebhookRead]
            Successful operation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks/{encode_path_param(id)}",
            method="PATCH",
            params={
                "update_mask": update_mask,
            },
            json={
                "name": name,
                "state": state,
                "subscribed_events": convert_and_respect_annotation_metadata(
                    object_=subscribed_events,
                    annotation=typing.Sequence[WebhookUpdateSubscribedEventsItem],
                    direction="write",
                ),
                "uri": uri,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookRead,
                    parse_obj_as(
                        type_=WebhookRead,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def rotate_signing_secret(
        self,
        id: str,
        *,
        revocation_behavior: typing.Optional[RotateSigningSecretRequestRevocationBehavior] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RotateSigningSecretResponse]:
        """
        Generates a new signing secret for a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook for which to generate a signing secret.
            Format: `{webhook_id}`

        revocation_behavior : typing.Optional[RotateSigningSecretRequestRevocationBehavior]
            Optional. The revocation behavior for previous signing secrets.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RotateSigningSecretResponse]
            Successful operation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks/{encode_path_param(id)}:rotateSigningSecret",
            method="POST",
            json={
                "revocation_behavior": revocation_behavior,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RotateSigningSecretResponse,
                    parse_obj_as(
                        type_=RotateSigningSecretResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def ping(
        self, id: str, *, request: PingWebhookRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PingWebhookResponse]:
        """
        Sends a ping event to a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to ping.
            Format: `{webhook_id}`

        request : PingWebhookRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PingWebhookResponse]
            Successful operation
        """
        _response = self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks/{encode_path_param(id)}:ping",
            method="POST",
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PingWebhookResponse,
                    parse_obj_as(
                        type_=PingWebhookResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawFernWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        page_size: typing.Optional[int] = None,
        page_token: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListWebhooksResponse]:
        """
        Lists all Webhooks.

        Parameters
        ----------
        page_size : typing.Optional[int]
            Optional. The maximum number of webhooks to return. The service may return fewer than
            this value. If unspecified, at most 50 webhooks will be returned.
            The maximum value is 1000.

        page_token : typing.Optional[str]
            Optional. A page token, received from a previous `ListWebhooks` call.
            Provide this to retrieve the subsequent page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListWebhooksResponse]
            Successful operation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks",
            method="GET",
            params={
                "page_size": page_size,
                "page_token": page_token,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListWebhooksResponse,
                    parse_obj_as(
                        type_=ListWebhooksResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        subscribed_events: typing.Sequence[WebhookSubscribedEventsItem],
        uri: str,
        name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WebhookRead]:
        """
        Creates a new Webhook.

        Parameters
        ----------
        subscribed_events : typing.Sequence[WebhookSubscribedEventsItem]
            Required. The events that the webhook is subscribed to.
            Available events:
            - batch.succeeded
            - batch.expired
            - batch.failed
            - interaction.requires_action
            - interaction.completed
            - interaction.failed
            - video.generated

        uri : str
            Required. The URI to which webhook events will be sent.

        name : typing.Optional[str]
            Optional. The user-provided name of the webhook.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WebhookRead]
            Successful operation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks",
            method="POST",
            json={
                "name": name,
                "subscribed_events": convert_and_respect_annotation_metadata(
                    object_=subscribed_events,
                    annotation=typing.Sequence[WebhookSubscribedEventsItem],
                    direction="write",
                ),
                "uri": uri,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookRead,
                    parse_obj_as(
                        type_=WebhookRead,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WebhookRead]:
        """
        Gets a specific Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WebhookRead]
            Successful operation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookRead,
                    parse_obj_as(
                        type_=WebhookRead,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[Empty]:
        """
        Deletes a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to delete.
            Format: `{webhook_id}`

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[Empty]
            Successful operation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    Empty,
                    parse_obj_as(
                        type_=Empty,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        id: str,
        *,
        update_mask: typing.Optional[str] = None,
        name: typing.Optional[str] = OMIT,
        state: typing.Optional[WebhookUpdateState] = OMIT,
        subscribed_events: typing.Optional[typing.Sequence[WebhookUpdateSubscribedEventsItem]] = OMIT,
        uri: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WebhookRead]:
        """
        Updates an existing Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to update.

        update_mask : typing.Optional[str]
            Optional. The list of fields to update.

        name : typing.Optional[str]
            Optional. The user-provided name of the webhook.

        state : typing.Optional[WebhookUpdateState]
            Optional. The state of the webhook.

        subscribed_events : typing.Optional[typing.Sequence[WebhookUpdateSubscribedEventsItem]]
            Optional. The events that the webhook is subscribed to.
            Available events:
            - batch.succeeded
            - batch.expired
            - batch.failed
            - interaction.requires_action
            - interaction.completed
            - interaction.failed
            - video.generated

        uri : typing.Optional[str]
            Optional. The URI to which webhook events will be sent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WebhookRead]
            Successful operation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks/{encode_path_param(id)}",
            method="PATCH",
            params={
                "update_mask": update_mask,
            },
            json={
                "name": name,
                "state": state,
                "subscribed_events": convert_and_respect_annotation_metadata(
                    object_=subscribed_events,
                    annotation=typing.Sequence[WebhookUpdateSubscribedEventsItem],
                    direction="write",
                ),
                "uri": uri,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WebhookRead,
                    parse_obj_as(
                        type_=WebhookRead,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def rotate_signing_secret(
        self,
        id: str,
        *,
        revocation_behavior: typing.Optional[RotateSigningSecretRequestRevocationBehavior] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RotateSigningSecretResponse]:
        """
        Generates a new signing secret for a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook for which to generate a signing secret.
            Format: `{webhook_id}`

        revocation_behavior : typing.Optional[RotateSigningSecretRequestRevocationBehavior]
            Optional. The revocation behavior for previous signing secrets.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RotateSigningSecretResponse]
            Successful operation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks/{encode_path_param(id)}:rotateSigningSecret",
            method="POST",
            json={
                "revocation_behavior": revocation_behavior,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RotateSigningSecretResponse,
                    parse_obj_as(
                        type_=RotateSigningSecretResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def ping(
        self, id: str, *, request: PingWebhookRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PingWebhookResponse]:
        """
        Sends a ping event to a Webhook.

        Parameters
        ----------
        id : str
            Required. The ID of the webhook to ping.
            Format: `{webhook_id}`

        request : PingWebhookRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PingWebhookResponse]
            Successful operation
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"{encode_path_param(self._client_wrapper._api_version)}/webhooks/{encode_path_param(id)}:ping",
            method="POST",
            json=request,
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PingWebhookResponse,
                    parse_obj_as(
                        type_=PingWebhookResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
