# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import os
import typing

import httpx
from .core.api_error import ApiError
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .environment import GeminiNextGenAPIClientEnvironment

if typing.TYPE_CHECKING:
    from .fern_agents.client import AsyncFernAgentsClient, FernAgentsClient
    from .fern_interactions.client import AsyncFernInteractionsClient, FernInteractionsClient
    from .fern_webhooks.client import AsyncFernWebhooksClient, FernWebhooksClient


class GeminiNextGenAPIClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : GeminiNextGenAPIClientEnvironment
        The environment to use for requests from the client. from .environment import GeminiNextGenAPIClientEnvironment



        Defaults to GeminiNextGenAPIClientEnvironment.DEFAULT



    api_version : typing.Optional[str]
    api_key : typing.Optional[str]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    api_revision : typing.Optional[str]
    Examples
    --------
    from google.genai._fern_interactions import GeminiNextGenAPIClient

    client = GeminiNextGenAPIClient(
        "v1beta",
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: GeminiNextGenAPIClientEnvironment = GeminiNextGenAPIClientEnvironment.DEFAULT,
        api_version: typing.Optional[str] = "v1beta",
        api_key: typing.Optional[str] = os.getenv("GEMINI_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
        api_revision: typing.Optional[str] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if api_key is None:
            raise ApiError(
                body="The client must be instantiated be either passing in api_key or setting GEMINI_API_KEY"
            )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_version=api_version,
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            logging=logging,
            api_revision=api_revision,
        )
        self._fern_interactions: typing.Optional[FernInteractionsClient] = None
        self._fern_webhooks: typing.Optional[FernWebhooksClient] = None
        self._fern_agents: typing.Optional[FernAgentsClient] = None

    @property
    def fern_interactions(self):
        if self._fern_interactions is None:
            from .fern_interactions.client import FernInteractionsClient  # noqa: E402

            self._fern_interactions = FernInteractionsClient(client_wrapper=self._client_wrapper)
        return self._fern_interactions

    @property
    def fern_webhooks(self):
        if self._fern_webhooks is None:
            from .fern_webhooks.client import FernWebhooksClient  # noqa: E402

            self._fern_webhooks = FernWebhooksClient(client_wrapper=self._client_wrapper)
        return self._fern_webhooks

    @property
    def fern_agents(self):
        if self._fern_agents is None:
            from .fern_agents.client import FernAgentsClient  # noqa: E402

            self._fern_agents = FernAgentsClient(client_wrapper=self._client_wrapper)
        return self._fern_agents


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncGeminiNextGenAPIClient:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : GeminiNextGenAPIClientEnvironment
        The environment to use for requests from the client. from .environment import GeminiNextGenAPIClientEnvironment



        Defaults to GeminiNextGenAPIClientEnvironment.DEFAULT



    api_version : typing.Optional[str]
    api_key : typing.Optional[str]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    max_retries : typing.Optional[int]
        The default maximum number of retries for failed requests. Defaults to 2. Per-request `max_retries` in `request_options` takes precedence over this value.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    api_revision : typing.Optional[str]
    Examples
    --------
    from google.genai._fern_interactions import AsyncGeminiNextGenAPIClient

    client = AsyncGeminiNextGenAPIClient(
        "v1beta",
        api_key="YOUR_API_KEY",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: GeminiNextGenAPIClientEnvironment = GeminiNextGenAPIClientEnvironment.DEFAULT,
        api_version: typing.Optional[str] = "v1beta",
        api_key: typing.Optional[str] = os.getenv("GEMINI_API_KEY"),
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        max_retries: typing.Optional[int] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
        api_revision: typing.Optional[str] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        _defaulted_max_retries = max_retries if max_retries is not None else 2
        if api_key is None:
            raise ApiError(
                body="The client must be instantiated be either passing in api_key or setting GEMINI_API_KEY"
            )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            api_version=api_version,
            api_key=api_key,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            max_retries=_defaulted_max_retries,
            logging=logging,
            api_revision=api_revision,
        )
        self._fern_interactions: typing.Optional[AsyncFernInteractionsClient] = None
        self._fern_webhooks: typing.Optional[AsyncFernWebhooksClient] = None
        self._fern_agents: typing.Optional[AsyncFernAgentsClient] = None

    @property
    def fern_interactions(self):
        if self._fern_interactions is None:
            from .fern_interactions.client import AsyncFernInteractionsClient  # noqa: E402

            self._fern_interactions = AsyncFernInteractionsClient(client_wrapper=self._client_wrapper)
        return self._fern_interactions

    @property
    def fern_webhooks(self):
        if self._fern_webhooks is None:
            from .fern_webhooks.client import AsyncFernWebhooksClient  # noqa: E402

            self._fern_webhooks = AsyncFernWebhooksClient(client_wrapper=self._client_wrapper)
        return self._fern_webhooks

    @property
    def fern_agents(self):
        if self._fern_agents is None:
            from .fern_agents.client import AsyncFernAgentsClient  # noqa: E402

            self._fern_agents = AsyncFernAgentsClient(client_wrapper=self._client_wrapper)
        return self._fern_agents


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: GeminiNextGenAPIClientEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
