# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Dict, List, Union, Optional, Iterable
from typing_extensions import Literal, TypeAlias, TypedDict, Required
from .._models import BaseModel

from .allowed_tools import AllowedTools
from .environment_param import EnvironmentParam
from .interaction_create_params import Environment
from .tool import Tool
from .tool_param import ToolParam

__all__ = ["Agent", "AgentGetParams", "AgentParam", "BaseEnvironment", "ToolCodeExecution", "ToolGoogleSearch", "ToolMCPServer", "ToolURLContext"]


class Agent(BaseModel):
    """An agent definition for the CreateAgent API.
This message is the target for annotation-parser-based JSON parsing.
New format:
  {
    "id": "customer-sentinel",
    "base_agent": "",
    "system_instruction": "...",
    "base_environment": { "type": "remote", "sources": [...] },
    "tools": [ {"type": "code_execution"} ]
  }"""

    base_agent: Optional[str] = None
    """The base agent to extend."""


    base_environment: Optional[Union[Environment, str]] = None
    """The environment configuration for the agent."""


    description: Optional[str] = None
    """Agent description for developers to quickly read and understand."""


    id: Optional[str] = None
    """The unique identifier for the agent."""


    system_instruction: Optional[str] = None
    """System instruction for the agent."""


    tools: Optional[List[Tool]] = None
    """The tools available to the agent."""



class AgentGetParams(TypedDict, total=False):
    """Parameters for AgentGetParams"""

    id: Required[str]

    api_version: str
    """Which version of the API to use."""



class AgentParam(TypedDict, total=False):
    """TypedDict parameter equivalent for Agent."""

    base_agent: str
    """The base agent to extend."""


    base_environment: Union[EnvironmentParam, str]
    """The environment configuration for the agent."""


    description: str
    """Agent description for developers to quickly read and understand."""


    id: str
    """The unique identifier for the agent."""


    system_instruction: str
    """System instruction for the agent."""


    tools: Iterable[ToolParam]
    """The tools available to the agent."""



BaseEnvironment: TypeAlias = Union[str, Environment]

class ToolCodeExecution(BaseModel):
    """A tool that can be used by the model to execute code."""

    type: Literal["code_execution"]


class ToolGoogleSearch(BaseModel):
    """A tool that can be used by the model to search Google."""

    search_types: Optional[List[Literal["web_search", "image_search", "enterprise_web_search"]]] = None
    """The types of search grounding to enable."""


    type: Literal["google_search"]


class ToolMCPServer(BaseModel):
    """A MCPServer is a server that can be called by the model to perform actions."""

    allowed_tools: Optional[List[AllowedTools]] = None
    """The allowed tools."""


    headers: Optional[Dict[str, str]] = None
    """Optional: Fields for authentication headers, timeouts, etc., if needed."""


    name: Optional[str] = None
    """The name of the MCPServer."""


    type: Literal["mcp_server"]

    url: Optional[str] = None
    """The full URL for the MCPServer endpoint.
Example: "https://api.example.com/mcp" """



class ToolURLContext(BaseModel):
    """A tool that can be used by the model to fetch URL context."""

    type: Literal["url_context"]

