# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Union, Iterable
from typing_extensions import TypedDict

from .environment_param import EnvironmentParam
from .tool_param import ToolParam

__all__ = ["AgentCreateParams"]


class AgentCreateParams(TypedDict, total=False):
    """An agent definition for the CreateAgent API.
This message is the target for annotation-parser-based JSON parsing.
New format:
  {
    "id": "customer-sentinel",
    "base_agent": "",
    "system_instruction": "...",
    "base_environment": { "type": "remote", "sources": [...] },
    "tools": [ {"type": "code_execution"} ]
  }"""

    base_agent: str
    """The base agent to extend."""


    base_environment: Union[EnvironmentParam, str]
    """The environment configuration for the agent."""


    description: str
    """Agent description for developers to quickly read and understand."""


    id: str
    """The unique identifier for the agent."""


    system_instruction: str
    """System instruction for the agent."""


    tools: Iterable[ToolParam]
    """The tools available to the agent."""


    api_version: str
    """Which version of the API to use."""


