# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Iterable
from typing_extensions import TypedDict

from .tool_choice_type_param import ToolChoiceTypeParam

__all__ = ["AllowedToolsParam"]


class AllowedToolsParam(TypedDict, total=False):
    """TypedDict parameter equivalent for AllowedTools."""

    mode: ToolChoiceTypeParam
    """The mode of the tool choice."""


    tools: Iterable[str]
    """The names of the allowed tools."""


