# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Optional
from typing_extensions import Literal
from .._models import BaseModel

from .code_execution_call_arguments import Arguments

__all__ = ["CodeExecutionCallStep"]


class CodeExecutionCallStep(BaseModel):
    """Code execution call step."""

    arguments: Arguments
    """Required. The arguments to pass to the code execution."""


    id: str
    """Required. A unique ID for this specific tool call."""


    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["code_execution_call"]

