# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Any, Dict, Union
from typing_extensions import Literal, TypeAlias, TypedDict, Required

from google.genai._common import SequenceNotStr

__all__ = ["NetworkAllowlistParam", "NetworkAllowlistAllowlistParam", "NetworkAllowlistAllowlistParam", "NetworkAllowlistParam", "SourceParam", "EnvironmentParam"]


NetworkAllowlistParam: TypeAlias = Union[Any, Literal["disabled"]]

class NetworkAllowlistAllowlistParam(TypedDict, total=False):
    """TypedDict parameter equivalent for AllowlistEntry."""

    domain: Required[str]
    """Domain to allow outbound requests to. Supports wildcards (e.g. '*.googleapis.com'). Use '*' to allow all domains."""


    transform: SequenceNotStr[Dict[str, str]]
    """Headers to inject on all outbound requests matching this domain. Each entry is a flat {header_name: header_value} object. The egress proxy injects these automatically."""



class NetworkAllowlistAllowlistParam(TypedDict, total=False):
    """TypedDict parameter equivalent for AllowlistEntry."""

    domain: Required[str]
    """Domain to allow outbound requests to. Supports wildcards (e.g. '*.googleapis.com'). Use '*' to allow all domains."""


    transform: SequenceNotStr[Dict[str, str]]
    """Headers to inject on all outbound requests matching this domain. Each entry is a flat {header_name: header_value} object. The egress proxy injects these automatically."""



NetworkAllowlistParam: TypeAlias = Union[Any, Literal["disabled"]]

class SourceParam(TypedDict, total=False):
    """TypedDict parameter equivalent for Source."""

    content: str
    """The inline content if `type` is `INLINE`."""


    encoding: str
    """Optional encoding for inline content (e.g. `base64`)."""


    source: str
    """The source of the environment.
For GCS, this is the GCS path.
For GitHub, this is the GitHub path."""


    target: str
    """Where the source should appear in the environment."""


    type: Literal["gcs", "inline", "repository", "skill_registry"]


class EnvironmentParam(TypedDict, total=False):
    """TypedDict parameter equivalent for EnvironmentConfig."""

    network: Union[NetworkAllowlistParam, Literal["disabled"]]
    """Network configuration for the environment."""


    sources: SequenceNotStr[SourceParam]

    type: Required[Literal["remote"]]

