# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Dict
from typing_extensions import Literal, TypedDict, Required

__all__ = ["FunctionCallStepParam"]


class FunctionCallStepParam(TypedDict, total=False):
    """TypedDict parameter equivalent for FunctionCallStep."""

    arguments: Required[Dict[str, object]]
    """Required. The arguments to pass to the function."""


    id: Required[str]
    """Required. A unique ID for this specific tool call."""


    name: Required[str]
    """Required. The name of the tool to call."""


    signature: str
    """A signature hash for backend validation."""


    type: Required[Literal["function_call"]]

