# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing_extensions import TypedDict, Required

__all__ = ["InteractionGetParams"]


class InteractionGetParams(TypedDict, total=False):
    """Parameters for InteractionGetParams"""

    id: Required[str]
    """The unique identifier of the interaction to retrieve."""


    stream: bool
    """If set to true, the generated content will be streamed incrementally."""


    last_event_id: str
    """Optional. If set, resumes the interaction stream from the next chunk after the event marked by the event id. Can only be used if `stream` is true."""


    include_input: bool
    """If set to true, includes the input in the response."""


    api_version: str
    """Which version of the API to use."""


