# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import List, Union, Optional, Iterable
from typing_extensions import Literal, TypeAlias, TypedDict, Required
from .._models import BaseModel

from .audio_response_format import AudioResponseFormat
from .content import Content
from .deep_research_agent_config import DeepResearchAgentConfig
from .dynamic_agent_config import DynamicAgentConfig
from .environment import NetworkAllowlist
from .environment import Source
from .generation_config import GenerationConfig
from .image_response_format import ImageResponseFormat
from .interaction import AgentOption
from .interaction import ServiceTier
from .model import Model
from .response_modality import ResponseModality
from .step import Step
from .text_response_format import TextResponseFormat
from .tool import Tool
from .usage import Usage
from .webhook_config import WebhookConfig
from google.genai._common import SequenceNotStr

__all__ = ["Environment", "InteractionsInput", "ResponseFormat", "ResponseFormatList", "CreateAgentInteractionParams", "CreateModelInteractionParams", "InteractionCreateParams"]


class Environment(BaseModel):
    """Configuration for a custom environment."""

    network: Optional[Union[NetworkAllowlist, Literal["disabled"]]] = None
    """Network configuration for the environment."""


    sources: Optional[List[Source]] = None

    type: Literal["remote"]


InteractionsInput: TypeAlias = Union[str, List[Step], List[Content], Content]

ResponseFormat: TypeAlias = Union[AudioResponseFormat, TextResponseFormat, ImageResponseFormat, object]

class ResponseFormatList(BaseModel):
    """The ResponseFormatList resource."""

    pass


class CreateAgentInteractionParams(TypedDict, total=False):
    """Parameters for creating agent interactions"""

    agent: Required[AgentOption]
    """The name of the `Agent` used for generating the interaction."""


    background: bool
    """Input only. Whether to run the model interaction in the background."""


    store: bool
    """Input only. Whether to store the response and request for later retrieval."""


    stream: bool
    """Input only. Whether the interaction will be streamed."""


    created: str
    """Required. Output only. The time at which the response was created in ISO 8601 format
(YYYY-MM-DDThh:mm:ssZ)."""


    environment: Union[str, Environment]
    """The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID."""


    environment_id: str
    """Output only. The environment ID for the interaction. Only populated if environment
config is set in the request."""


    id: str
    """Required. Output only. A unique identifier for the interaction completion."""


    input: Required[InteractionsInput]

    previous_interaction_id: str
    """The ID of the previous interaction, if any."""


    response_format: Union[ResponseFormatList, ResponseFormat]
    """Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field."""


    response_mime_type: str
    """The mime type of the response. This is required if response_format is set."""


    response_modalities: SequenceNotStr[ResponseModality]
    """The requested modalities of the response (TEXT, IMAGE, AUDIO)."""


    role: str
    """Output only. The role of the interaction."""


    service_tier: ServiceTier
    """The service tier for the interaction."""


    status: Literal["in_progress", "requires_action", "completed", "failed", "cancelled", "incomplete", "budget_exceeded"]
    """Required. Output only. The status of the interaction."""


    system_instruction: str
    """System instruction for the interaction."""


    tools: Iterable[Tool]
    """A list of tool declarations the model may call during interaction."""


    updated: str
    """Required. Output only. The time at which the response was last updated in ISO 8601 format
(YYYY-MM-DDThh:mm:ssZ)."""


    usage: Usage
    """Output only. Statistics on the interaction request's token usage."""


    webhook_config: WebhookConfig
    """Optional. Webhook configuration for receiving notifications when the
interaction completes."""


    agent_config: Union[DynamicAgentConfig, DeepResearchAgentConfig]
    """Configuration parameters for the agent interaction."""



class CreateModelInteractionParams(TypedDict, total=False):
    """Parameters for creating model interactions"""

    model: Required[Model]
    """The name of the `Model` used for generating the interaction."""


    background: bool
    """Input only. Whether to run the model interaction in the background."""


    store: bool
    """Input only. Whether to store the response and request for later retrieval."""


    stream: bool
    """Input only. Whether the interaction will be streamed."""


    created: str
    """Required. Output only. The time at which the response was created in ISO 8601 format
(YYYY-MM-DDThh:mm:ssZ)."""


    environment: Union[str, Environment]
    """The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID."""


    environment_id: str
    """Output only. The environment ID for the interaction. Only populated if environment
config is set in the request."""


    id: str
    """Required. Output only. A unique identifier for the interaction completion."""


    input: Required[InteractionsInput]

    previous_interaction_id: str
    """The ID of the previous interaction, if any."""


    response_format: Union[ResponseFormatList, ResponseFormat]
    """Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field."""


    response_mime_type: str
    """The mime type of the response. This is required if response_format is set."""


    response_modalities: SequenceNotStr[ResponseModality]
    """The requested modalities of the response (TEXT, IMAGE, AUDIO)."""


    role: str
    """Output only. The role of the interaction."""


    service_tier: ServiceTier
    """The service tier for the interaction."""


    status: Literal["in_progress", "requires_action", "completed", "failed", "cancelled", "incomplete", "budget_exceeded"]
    """Required. Output only. The status of the interaction."""


    system_instruction: str
    """System instruction for the interaction."""


    tools: Iterable[Tool]
    """A list of tool declarations the model may call during interaction."""


    updated: str
    """Required. Output only. The time at which the response was last updated in ISO 8601 format
(YYYY-MM-DDThh:mm:ssZ)."""


    usage: Usage
    """Output only. Statistics on the interaction request's token usage."""


    webhook_config: WebhookConfig
    """Optional. Webhook configuration for receiving notifications when the
interaction completes."""


    generation_config: GenerationConfig
    """Input only. Configuration parameters for the model interaction."""



class InteractionCreateParams(TypedDict, total=False):
    """Parameters for InteractionCreateParams"""

    api_version: str
    """Which version of the API to use."""


