# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations

from datetime import datetime
from typing import Any, List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias, TypedDict, Required
from .._models import BaseModel
from .._utils import PropertyInfo

from .audio_response_format import AudioResponseFormat
from .audio_response_format_param import AudioResponseFormatParam
from .content import Content
from .content_param import ContentParam
from .deep_research_agent_config import DeepResearchAgentConfig
from .dynamic_agent_config import DynamicAgentConfig
from .error_event import Error
from .generation_config import GenerationConfig
from .image_response_format import ImageResponseFormat
from .image_response_format_param import ImageResponseFormatParam
from .interaction_create_params import Environment
from .interaction_create_params import InteractionsInput
from .interaction_create_params import ResponseFormat
from .interaction_create_params import ResponseFormatList
from .model import Model
from .response_modality import ResponseModality
from .step import Step
from .step_param import StepParam
from .text_response_format import TextResponseFormat
from .text_response_format_param import TextResponseFormatParam
from .tool import Tool
from .usage import Usage
from .webhook_config import WebhookConfig
from datetime import datetime
from google.genai._common import SequenceNotStr

__all__ = ["AgentConfig", "AgentOption", "AgentOptionParam", "CancelCancelInteractionByIdParams", "CancelCancelInteractionByIdResponse", "Input", "InputParam", "ServiceTier", "Interaction", "InteractionCreateResponse", "InteractionDeleteResponse", "InteractionEnvironment", "InteractionGetResponse", "InteractionResponseFormat", "InteractionsInputParam", "ResponseFormatListParam", "ResponseFormatParam", "ResponseFormatResponseFormatList", "ServiceTierParam", "Turn"]


AgentConfig: TypeAlias = Annotated[
    Union[DynamicAgentConfig, DeepResearchAgentConfig], PropertyInfo(discriminator="type")
]

AgentOption: TypeAlias = Union[str, Any, Any, Any]

AgentOptionParam: TypeAlias = Union[str, Any, Any, Any]

class CancelCancelInteractionByIdParams(TypedDict, total=False):
    """Parameters for CancelCancelInteractionByIdParams"""

    id: Required[str]
    """The unique identifier of the interaction to cancel."""


    api_version: str
    """Which version of the API to use."""



class CancelCancelInteractionByIdResponse(BaseModel):
    error: Optional[Error] = None


Input: TypeAlias = Union[str, List[Step], List[Content], Content]

InputParam: TypeAlias = Union[str, SequenceNotStr[StepParam], SequenceNotStr[ContentParam], ContentParam]

ServiceTier: TypeAlias = Literal["flex", "standard", "priority"]

class Interaction(BaseModel):
    """The Interaction resource."""

    model: Optional[Model] = None
    """The name of the `Model` used for generating the interaction."""


    agent: Optional[Union[Literal["deep-research-pro-preview-12-2025", "deep-research-preview-04-2026", "deep-research-max-preview-04-2026"], str]] = None
    """The name of the `Agent` used for generating the interaction."""


    created: datetime
    """Required. Output only. The time at which the response was created in ISO 8601 format
(YYYY-MM-DDThh:mm:ssZ)."""


    environment: Optional[Union[str, Environment]] = None
    """The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID."""


    environment_id: Optional[str] = None
    """Output only. The environment ID for the interaction. Only populated if environment
config is set in the request."""


    id: str
    """Required. Output only. A unique identifier for the interaction completion."""


    input: Optional[InteractionsInput] = None

    previous_interaction_id: Optional[str] = None
    """The ID of the previous interaction, if any."""


    response_format: Optional[Union[ResponseFormatList, ResponseFormat]] = None
    """Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field."""


    response_mime_type: Optional[str] = None
    """The mime type of the response. This is required if response_format is set."""


    response_modalities: Optional[List[ResponseModality]] = None
    """The requested modalities of the response (TEXT, IMAGE, AUDIO)."""


    role: Optional[str] = None
    """Output only. The role of the interaction."""


    service_tier: Optional[ServiceTier] = None
    """The service tier for the interaction."""


    status: Literal["in_progress", "requires_action", "completed", "failed", "cancelled", "incomplete", "budget_exceeded"]
    """Required. Output only. The status of the interaction."""


    steps: List[Step]
    """Required. Output only. The steps that make up the interaction."""


    system_instruction: Optional[str] = None
    """System instruction for the interaction."""


    tools: Optional[List[Tool]] = None
    """A list of tool declarations the model may call during interaction."""


    updated: datetime
    """Required. Output only. The time at which the response was last updated in ISO 8601 format
(YYYY-MM-DDThh:mm:ssZ)."""


    usage: Optional[Usage] = None
    """Output only. Statistics on the interaction request's token usage."""


    webhook_config: Optional[WebhookConfig] = None
    """Optional. Webhook configuration for receiving notifications when the
interaction completes."""


    generation_config: Optional[GenerationConfig] = None
    """Input only. Configuration parameters for the model interaction."""


    agent_config: Optional[Union[DynamicAgentConfig, DeepResearchAgentConfig]] = None
    """Configuration parameters for the agent interaction."""



class InteractionCreateResponse(BaseModel):
    error: Optional[Error] = None


class InteractionDeleteResponse(BaseModel):
    error: Optional[Error] = None


InteractionEnvironment: TypeAlias = Union[str, Environment]

class InteractionGetResponse(BaseModel):
    error: Optional[Error] = None


ResponseFormat: TypeAlias = Union[
    List[ResponseFormatResponseFormatList],
    AudioResponseFormat,
    TextResponseFormat,
    ImageResponseFormat,
    object,
]

InteractionsInputParam: TypeAlias = Union[str, SequenceNotStr[StepParam], SequenceNotStr[ContentParam], ContentParam]

ResponseFormatListParam: TypeAlias = SequenceNotStr[ResponseFormat]

ResponseFormatParam: TypeAlias = Union[AudioResponseFormatParam, TextResponseFormatParam, ImageResponseFormatParam, Any]

class ResponseFormatResponseFormatList(BaseModel):
    """The ResponseFormatResponseFormatList resource."""

    pass


ServiceTierParam: TypeAlias = Literal["flex", "standard", "priority"]

class Turn(BaseModel):
    content: Optional[Union[List[Content], str]] = None

    role: Optional[str] = None
    """The originator of this turn. Must be user for input or model for
model output."""


