# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations

from datetime import datetime
from typing import Optional
from .._models import BaseModel

from datetime import datetime

__all__ = ["SigningSecret"]


class SigningSecret(BaseModel):
    """Represents a signing secret used to verify webhook payloads."""

    expire_time: Optional[datetime] = None
    """Output only. The expiration date of the signing secret."""


    truncated_secret: Optional[str] = None
    """Output only. The truncated version of the signing secret."""


