# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Dict, List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias
from .._models import BaseModel
from .._utils import PropertyInfo

from .annotation import Annotation
from .code_execution_call_arguments import CodeExecutionCallArguments
from .file_search_result_step import FileSearchResult
from .google_maps_call_arguments import GoogleMapsCallArguments
from .google_maps_result import GoogleMapsResult
from .google_search_call_arguments import GoogleSearchCallArguments
from .google_search_result import GoogleSearchResult
from .mcp_server_tool_result_step import ResultFunctionResultSubcontentList
from .thought_step import Summary
from .url_context_call_arguments import UrlContextCallArguments
from .url_context_result import UrlContextResult
from .usage import MediaResolution
from google.genai._common import Base64FileInput

__all__ = ["DeltaArgumentsDelta", "DeltaAudio", "DeltaCodeExecutionCall", "DeltaCodeExecutionResult", "DeltaDocument", "DeltaFileSearchCall", "DeltaFileSearchResult", "FunctionCallDelta", "DeltaFunctionResult", "DeltaGoogleMapsCall", "DeltaGoogleMapsResult", "DeltaGoogleSearchCall", "DeltaGoogleSearchResult", "DeltaImage", "DeltaMCPServerToolCall", "DeltaMCPServerToolResult", "DeltaTextAnnotationDelta", "DeltaText", "DeltaThoughtSignature", "DeltaThoughtSummary", "DeltaURLContextCall", "DeltaURLContextResult", "DeltaVideo", "ContentDeltaData", "ContentDelta", "Delta", "StepDelta"]


class DeltaArgumentsDelta(BaseModel):
    arguments: Optional[str] = None

    type: Literal["arguments_delta"]


class DeltaAudio(BaseModel):
    channels: Optional[int] = None
    """The number of audio channels."""


    data: Optional[Annotated[Union[str, Base64FileInput], PropertyInfo(format="base64")]] = None

    mime_type: Optional[Literal["audio/wav", "audio/mp3", "audio/aiff", "audio/aac", "audio/ogg", "audio/flac", "audio/mpeg", "audio/m4a", "audio/l16", "audio/opus", "audio/alaw", "audio/mulaw"]] = None

    rate: Optional[int] = None
    """Deprecated. Use sample_rate instead. The value is ignored."""


    sample_rate: Optional[int] = None
    """The sample rate of the audio."""


    type: Literal["audio"]

    uri: Optional[str] = None


class DeltaCodeExecutionCall(BaseModel):
    arguments: CodeExecutionCallArguments

    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["code_execution_call"]


class DeltaCodeExecutionResult(BaseModel):
    is_error: Optional[bool] = None

    result: str

    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["code_execution_result"]


class DeltaDocument(BaseModel):
    data: Optional[Annotated[Union[str, Base64FileInput], PropertyInfo(format="base64")]] = None

    mime_type: Optional[Literal["application/pdf"]] = None

    type: Literal["document"]

    uri: Optional[str] = None


class DeltaFileSearchCall(BaseModel):
    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["file_search_call"]


class DeltaFileSearchResult(BaseModel):
    result: List[FileSearchResult]

    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["file_search_result"]


class FunctionCallDelta(BaseModel):
    arguments: Dict[str, object]

    id: str
    """Required. A unique ID for this specific tool call."""


    name: str

    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["function_call"]


class DeltaFunctionResult(BaseModel):
    call_id: str
    """Required. ID to match the ID from the function call block."""


    is_error: Optional[bool] = None

    name: Optional[str] = None

    result: Union[List[ResultFunctionResultSubcontentList], str, object]

    type: Literal["function_result"]


class DeltaGoogleMapsCall(BaseModel):
    arguments: Optional[GoogleMapsCallArguments] = None
    """The arguments to pass to the Google Maps tool."""


    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["google_maps_call"]


class DeltaGoogleMapsResult(BaseModel):
    result: Optional[List[GoogleMapsResult]] = None
    """The results of the Google Maps."""


    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["google_maps_result"]


class DeltaGoogleSearchCall(BaseModel):
    arguments: GoogleSearchCallArguments

    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["google_search_call"]


class DeltaGoogleSearchResult(BaseModel):
    is_error: Optional[bool] = None

    result: List[GoogleSearchResult]

    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["google_search_result"]


class DeltaImage(BaseModel):
    data: Optional[Annotated[Union[str, Base64FileInput], PropertyInfo(format="base64")]] = None

    mime_type: Optional[Literal["image/png", "image/jpeg", "image/webp", "image/heic", "image/heif", "image/gif", "image/bmp", "image/tiff"]] = None

    resolution: Optional[MediaResolution] = None
    """The resolution of the media."""


    type: Literal["image"]

    uri: Optional[str] = None


class DeltaMCPServerToolCall(BaseModel):
    arguments: Dict[str, object]

    name: str

    server_name: str

    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["mcp_server_tool_call"]


class DeltaMCPServerToolResult(BaseModel):
    name: Optional[str] = None

    result: Union[List[ResultFunctionResultSubcontentList], str, object]

    server_name: Optional[str] = None

    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["mcp_server_tool_result"]


class DeltaTextAnnotationDelta(BaseModel):
    annotations: Optional[List[Annotation]] = None
    """Citation information for model-generated content."""


    type: Literal["text_annotation_delta"]


class DeltaText(BaseModel):
    text: str

    type: Literal["text"]


class DeltaThoughtSignature(BaseModel):
    signature: Optional[str] = None
    """Signature to match the backend source to be part of the generation."""


    type: Literal["thought_signature"]


class DeltaThoughtSummary(BaseModel):
    content: Optional[Summary] = None
    """A new summary item to be added to the thought."""


    type: Literal["thought_summary"]


class DeltaURLContextCall(BaseModel):
    arguments: UrlContextCallArguments

    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["url_context_call"]


class DeltaURLContextResult(BaseModel):
    is_error: Optional[bool] = None

    result: List[UrlContextResult]

    signature: Optional[str] = None
    """A signature hash for backend validation."""


    type: Literal["url_context_result"]


class DeltaVideo(BaseModel):
    data: Optional[Annotated[Union[str, Base64FileInput], PropertyInfo(format="base64")]] = None

    mime_type: Optional[Literal["video/mp4", "video/mpeg", "video/mpg", "video/mov", "video/avi", "video/x-flv", "video/webm", "video/wmv", "video/3gpp"]] = None

    resolution: Optional[MediaResolution] = None
    """The resolution of the media."""


    type: Literal["video"]

    uri: Optional[str] = None


ContentDeltaData: TypeAlias = Annotated[
    Union[DeltaText, DeltaImage, DeltaAudio, DeltaDocument, DeltaVideo, DeltaThoughtSummary, DeltaThoughtSignature, FunctionCallDelta, DeltaCodeExecutionCall, DeltaURLContextCall, DeltaGoogleSearchCall, DeltaMCPServerToolCall, DeltaFileSearchCall, DeltaGoogleMapsCall, DeltaFunctionResult, DeltaCodeExecutionResult, DeltaURLContextResult, DeltaGoogleSearchResult, DeltaMCPServerToolResult, DeltaFileSearchResult, DeltaGoogleMapsResult, DeltaTextAnnotationDelta], PropertyInfo(discriminator="type")
]

class ContentDelta(BaseModel):
    delta: ContentDeltaData

    event_id: Optional[str] = None
    """The event_id token to be used to resume the interaction stream, from
this event."""


    event_type: Literal["content.delta"]

    index: int


Delta: TypeAlias = Annotated[
    Union[DeltaText, DeltaImage, DeltaAudio, DeltaDocument, DeltaVideo, DeltaThoughtSummary, DeltaThoughtSignature, DeltaTextAnnotationDelta, DeltaArgumentsDelta, DeltaCodeExecutionCall, DeltaURLContextCall, DeltaGoogleSearchCall, DeltaMCPServerToolCall, DeltaFileSearchCall, DeltaGoogleMapsCall, DeltaCodeExecutionResult, DeltaURLContextResult, DeltaGoogleSearchResult, DeltaMCPServerToolResult, DeltaFileSearchResult, DeltaGoogleMapsResult, DeltaFunctionResult], PropertyInfo(discriminator="type")
]

class StepDelta(BaseModel):
    delta: Delta

    event_id: Optional[str] = None
    """The event_id token to be used to resume the interaction stream, from
this event."""


    event_type: Literal["step.delta"]

    index: int

