# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Union
from typing_extensions import Annotated, TypeAlias
from .._utils import PropertyInfo

from .code_execution_call_step import CodeExecutionCallStep
from .code_execution_result_step import CodeExecutionResultStep
from .file_search_call_step import FileSearchCallStep
from .file_search_result_step import FileSearchResultStep
from .function_call_step import FunctionCallStep
from .function_result_step import FunctionResultStep
from .google_maps_call_step import GoogleMapsCallStep
from .google_maps_result_step import GoogleMapsResultStep
from .google_search_call_step import GoogleSearchCallStep
from .google_search_result_step import GoogleSearchResultStep
from .mcp_server_tool_call_step import MCPServerToolCallStep
from .mcp_server_tool_result_step import MCPServerToolResultStep
from .model_output_step import ModelOutputStep
from .thought_step import ThoughtStep
from .url_context_call_step import URLContextCallStep
from .url_context_result_step import UrlContextResultStep
from .user_input_step import UserInputStep

__all__ = ["Step"]


Step: TypeAlias = Annotated[
    Union[UserInputStep, ModelOutputStep, ThoughtStep, FunctionCallStep, CodeExecutionCallStep, URLContextCallStep, MCPServerToolCallStep, GoogleSearchCallStep, FileSearchCallStep, GoogleMapsCallStep, FunctionResultStep, CodeExecutionResultStep, UrlContextResultStep, GoogleSearchResultStep, MCPServerToolResultStep, FileSearchResultStep, GoogleMapsResultStep], PropertyInfo(discriminator="type")
]
