# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Any, Dict, Optional
from pydantic import Field as FieldInfo
from typing_extensions import Literal
from .._models import BaseModel

__all__ = ["TextResponseFormat"]


class TextResponseFormat(BaseModel):
    """Configuration for text output format."""

    mime_type: Optional[Literal["application/json", "text/plain"]] = None
    """The MIME type of the text output."""


    schema_: Optional[Dict[str, Any]] = FieldInfo(alias="schema", default=None)
    """The JSON schema that the output should conform to. Only applicable when
mime_type is application/json."""


    type: Literal["text"]

