# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Dict, List, Union, Iterable
from typing_extensions import Literal, TypeAlias, TypedDict, Required

from .allowed_tools_param import AllowedToolsParam
from .function_param import FunctionParam
from google.genai._common import SequenceNotStr

__all__ = ["CodeExecutionParam", "GoogleSearchParam", "McpServerParam", "UrlContextParam", "ToolParam", "ComputerUseParam", "FileSearchParam", "GoogleMapsParam", "RetrievalVertexAISearchConfig", "RetrievalParam", "ToolParam"]


class CodeExecutionParam(TypedDict, total=False):
    """TypedDict parameter equivalent for CodeExecution."""

    type: Required[Literal["code_execution"]]


class GoogleSearchParam(TypedDict, total=False):
    """TypedDict parameter equivalent for GoogleSearch."""

    search_types: SequenceNotStr[Literal["web_search", "image_search", "enterprise_web_search"]]
    """The types of search grounding to enable."""


    type: Required[Literal["google_search"]]


class McpServerParam(TypedDict, total=False):
    """TypedDict parameter equivalent for McpServer."""

    allowed_tools: Iterable[AllowedToolsParam]
    """The allowed tools."""


    headers: Dict[str, str]
    """Optional: Fields for authentication headers, timeouts, etc., if needed."""


    name: str
    """The name of the MCPServer."""


    type: Required[Literal["mcp_server"]]

    url: str
    """The full URL for the MCPServer endpoint.
Example: "https://api.example.com/mcp" """



class UrlContextParam(TypedDict, total=False):
    """TypedDict parameter equivalent for UrlContext."""

    type: Required[Literal["url_context"]]


ToolParam: TypeAlias = Union[CodeExecutionParam, GoogleSearchParam, UrlContextParam, McpServerParam]

class ComputerUseParam(TypedDict, total=False):
    """TypedDict parameter equivalent for ComputerUse."""

    environment: Literal["browser"]
    """The environment being operated."""


    excluded_predefined_functions: SequenceNotStr[str]
    """The list of predefined functions that are excluded from the model call."""


    type: Required[Literal["computer_use"]]


class FileSearchParam(TypedDict, total=False):
    """TypedDict parameter equivalent for FileSearch."""

    file_search_store_names: SequenceNotStr[str]
    """The file search store names to search."""


    metadata_filter: str
    """Metadata filter to apply to the semantic retrieval documents and chunks."""


    top_k: int
    """The number of semantic retrieval chunks to retrieve."""


    type: Required[Literal["file_search"]]


class GoogleMapsParam(TypedDict, total=False):
    """TypedDict parameter equivalent for GoogleMaps."""

    enable_widget: bool
    """Whether to return a widget context token in the tool call result of the
response."""


    latitude: float
    """The latitude of the user's location."""


    longitude: float
    """The longitude of the user's location."""


    type: Required[Literal["google_maps"]]


class RetrievalVertexAISearchConfig(TypedDict, total=False):
    """TypedDict parameter equivalent for VertexAISearchConfig."""

    datastores: List[str]
    """Optional. Used to specify Vertex AI Search datastores."""


    engine: str
    """Optional. Used to specify Vertex AI Search engine."""



class RetrievalParam(TypedDict, total=False):
    """TypedDict parameter equivalent for Retrieval."""

    retrieval_types: SequenceNotStr[Literal["vertex_ai_search"]]
    """The types of file retrieval to enable."""


    type: Required[Literal["retrieval"]]

    vertex_ai_search_config: RetrievalVertexAISearchConfig
    """Used to specify configuration for VertexAISearch."""



ToolParam: TypeAlias = Union[FunctionParam, CodeExecutionParam, UrlContextParam, ComputerUseParam, McpServerParam, GoogleSearchParam, FileSearchParam, GoogleMapsParam, RetrievalParam]
