# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Union, Optional
from typing_extensions import Literal, Annotated
from .._models import BaseModel
from .._utils import PropertyInfo

from .usage import MediaResolution
from google.genai._common import Base64FileInput

__all__ = ["VideoContent"]


class VideoContent(BaseModel):
    """A video content block."""

    data: Optional[Annotated[Union[str, Base64FileInput], PropertyInfo(format="base64")]] = None
    """The video content."""


    mime_type: Optional[Literal["video/mp4", "video/mpeg", "video/mpg", "video/mov", "video/avi", "video/x-flv", "video/webm", "video/wmv", "video/3gpp"]] = None
    """The mime type of the video."""


    resolution: Optional[MediaResolution] = None
    """The resolution of the media."""


    type: Literal["video"]

    uri: Optional[str] = None
    """The URI of the video."""


