# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations

from datetime import datetime
from typing import Any, List, Union, Optional
from typing_extensions import Literal, TypedDict, Required
from .._models import BaseModel

from .signing_secret import SigningSecret
from datetime import datetime
from google.genai._common import SequenceNotStr

__all__ = ["Webhook", "WebhookParam"]


class Webhook(BaseModel):
    """A Webhook resource."""

    create_time: Optional[datetime] = None
    """Output only. The timestamp when the webhook was created."""


    id: Optional[str] = None
    """Output only. The ID of the webhook."""


    name: Optional[str] = None
    """Optional. The user-provided name of the webhook."""


    new_signing_secret: Optional[str] = None
    """Output only. The new signing secret for the webhook. Only populated on create."""


    signing_secrets: Optional[List[SigningSecret]] = None
    """Output only. The signing secrets associated with this webhook."""


    state: Optional[Literal["enabled", "disabled", "disabled_due_to_failed_deliveries"]] = None
    """Output only. The state of the webhook."""


    subscribed_events: List[Union[str, Any, Any, Any, Any, Any, Any, Any]]
    """Required. The events that the webhook is subscribed to.
Available events:
- batch.succeeded
- batch.expired
- batch.failed
- interaction.requires_action
- interaction.completed
- interaction.failed
- video.generated"""


    update_time: Optional[datetime] = None
    """Output only. The timestamp when the webhook was last updated."""


    uri: str
    """Required. The URI to which webhook events will be sent."""



class WebhookParam(TypedDict, total=False):
    """TypedDict parameter equivalent for Webhook."""

    create_time: str
    """Output only. The timestamp when the webhook was created."""


    id: str
    """Output only. The ID of the webhook."""


    name: str
    """Optional. The user-provided name of the webhook."""


    new_signing_secret: str
    """Output only. The new signing secret for the webhook. Only populated on create."""


    signing_secrets: SequenceNotStr[SigningSecretParam]
    """Output only. The signing secrets associated with this webhook."""


    state: Literal["enabled", "disabled", "disabled_due_to_failed_deliveries"]
    """Output only. The state of the webhook."""


    subscribed_events: Required[SequenceNotStr[Union[str, Any, Any, Any, Any, Any, Any, Any]]]
    """Required. The events that the webhook is subscribed to.
Available events:
- batch.succeeded
- batch.expired
- batch.failed
- interaction.requires_action
- interaction.completed
- interaction.failed
- video.generated"""


    update_time: str
    """Output only. The timestamp when the webhook was last updated."""


    uri: Required[str]
    """Required. The URI to which webhook events will be sent."""


