# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing_extensions import TypedDict, Required
from .._models import BaseModel

__all__ = ["Body", "BodyParam", "Empty", "EmptyParam", "WebhookPingParams"]


class Body(TypedDict, total=False):
    pass


class BodyParam(TypedDict, total=False):
    """TypedDict parameter equivalent for Body."""

    pass


class Empty(BaseModel):
    """A generic empty message that you can re-use to avoid defining duplicated
empty messages in your APIs. A typical example is to use it as the request
or the response type of an API method. For instance:

    service Foo {
      rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
    }"""

    pass


class EmptyParam(TypedDict, total=False):
    """TypedDict parameter equivalent for Empty."""

    pass


class WebhookPingParams(TypedDict, total=False):
    """Request message for WebhookService.PingWebhook."""

    id: Required[str]
    """Required. The ID of the webhook to ping.
Format: `{webhook_id}`"""


    api_version: str
    """Which version of the API to use."""


    body: Body

