# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Code generated by the in-house datatype generator DO NOT EDIT.

from __future__ import annotations
from typing import Any, List, Union, Optional
from typing_extensions import Literal, TypedDict, Required
from .._models import BaseModel

from google.genai._common import SequenceNotStr

__all__ = ["WebhookUpdate", "WebhookUpdateParam", "WebhookUpdateParams"]


class WebhookUpdate(BaseModel):
    name: Optional[str] = None
    """Optional. The user-provided name of the webhook."""


    state: Optional[Literal["enabled", "disabled", "disabled_due_to_failed_deliveries"]] = None
    """Optional. The state of the webhook."""


    subscribed_events: Optional[List[Union[str, Any, Any, Any, Any, Any, Any, Any]]] = None
    """Optional. The events that the webhook is subscribed to.
Available events:
- batch.succeeded
- batch.expired
- batch.failed
- interaction.requires_action
- interaction.completed
- interaction.failed
- video.generated"""


    uri: Optional[str] = None
    """Optional. The URI to which webhook events will be sent."""



class WebhookUpdateParam(TypedDict, total=False):
    """TypedDict parameter equivalent for WebhookUpdate."""

    name: str
    """Optional. The user-provided name of the webhook."""


    state: Literal["enabled", "disabled", "disabled_due_to_failed_deliveries"]
    """Optional. The state of the webhook."""


    subscribed_events: SequenceNotStr[Union[str, Any, Any, Any, Any, Any, Any, Any]]
    """Optional. The events that the webhook is subscribed to.
Available events:
- batch.succeeded
- batch.expired
- batch.failed
- interaction.requires_action
- interaction.completed
- interaction.failed
- video.generated"""


    uri: str
    """Optional. The URI to which webhook events will be sent."""



class WebhookUpdateParams(TypedDict, total=False):
    """Parameters for WebhookUpdateParams"""

    name: str
    """Optional. The user-provided name of the webhook."""


    state: Literal["enabled", "disabled", "disabled_due_to_failed_deliveries"]
    """Optional. The state of the webhook."""


    subscribed_events: SequenceNotStr[Union[str, Any, Any, Any, Any, Any, Any, Any]]
    """Optional. The events that the webhook is subscribed to.
Available events:
- batch.succeeded
- batch.expired
- batch.failed
- interaction.requires_action
- interaction.completed
- interaction.failed
- video.generated"""


    uri: str
    """Optional. The URI to which webhook events will be sent."""


    id: Required[str]
    """Required. The ID of the webhook to update."""


    api_version: str
    """Which version of the API to use."""


    update_mask: str
    """Optional. The list of fields to update."""


