# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agent import Agent
    from .agent_base_environment import AgentBaseEnvironment
    from .agent_egress_allowlist import AgentEgressAllowlist
    from .agent_egress_rule import AgentEgressRule
    from .agent_option import AgentOption
    from .agent_option_one import AgentOptionOne
    from .agent_option_three import AgentOptionThree
    from .agent_option_two import AgentOptionTwo
    from .agent_tool import AgentTool
    from .allowed_tools import AllowedTools
    from .allowlist_entry import AllowlistEntry
    from .annotation import Annotation
    from .arguments_delta import ArgumentsDelta
    from .arguments_delta_type import ArgumentsDeltaType
    from .audio_content import AudioContent
    from .audio_content_mime_type import AudioContentMimeType
    from .audio_content_type import AudioContentType
    from .audio_delta import AudioDelta
    from .audio_delta_mime_type import AudioDeltaMimeType
    from .audio_delta_type import AudioDeltaType
    from .audio_response_format import AudioResponseFormat
    from .audio_response_format_delivery import AudioResponseFormatDelivery
    from .audio_response_format_mime_type import AudioResponseFormatMimeType
    from .audio_response_format_type import AudioResponseFormatType
    from .code_execution import CodeExecution
    from .code_execution_call_arguments import CodeExecutionCallArguments
    from .code_execution_call_arguments_language import CodeExecutionCallArgumentsLanguage
    from .code_execution_call_delta import CodeExecutionCallDelta
    from .code_execution_call_delta_type import CodeExecutionCallDeltaType
    from .code_execution_call_step import CodeExecutionCallStep
    from .code_execution_call_step_arguments import CodeExecutionCallStepArguments
    from .code_execution_call_step_arguments_language import CodeExecutionCallStepArgumentsLanguage
    from .code_execution_call_step_type import CodeExecutionCallStepType
    from .code_execution_result_delta import CodeExecutionResultDelta
    from .code_execution_result_delta_type import CodeExecutionResultDeltaType
    from .code_execution_result_step import CodeExecutionResultStep
    from .code_execution_result_step_type import CodeExecutionResultStepType
    from .code_execution_type import CodeExecutionType
    from .computer_use import ComputerUse
    from .computer_use_environment import ComputerUseEnvironment
    from .computer_use_type import ComputerUseType
    from .content import Content
    from .content_delta import ContentDelta
    from .content_delta_data import ContentDeltaData
    from .content_delta_event_type import ContentDeltaEventType
    from .content_start import ContentStart
    from .content_start_event_type import ContentStartEventType
    from .content_stop import ContentStop
    from .content_stop_event_type import ContentStopEventType
    from .create_agent_interaction_params import CreateAgentInteractionParams
    from .create_agent_interaction_params_agent_config import CreateAgentInteractionParamsAgentConfig
    from .create_agent_interaction_params_environment import CreateAgentInteractionParamsEnvironment
    from .create_agent_interaction_params_response_format import CreateAgentInteractionParamsResponseFormat
    from .create_model_interaction_params import CreateModelInteractionParams
    from .create_model_interaction_params_environment import CreateModelInteractionParamsEnvironment
    from .create_model_interaction_params_response_format import CreateModelInteractionParamsResponseFormat
    from .deep_research_agent_config import DeepResearchAgentConfig
    from .deep_research_agent_config_type import DeepResearchAgentConfigType
    from .deep_research_agent_config_visualization import DeepResearchAgentConfigVisualization
    from .document_content import DocumentContent
    from .document_content_mime_type import DocumentContentMimeType
    from .document_content_type import DocumentContentType
    from .document_delta import DocumentDelta
    from .document_delta_mime_type import DocumentDeltaMimeType
    from .document_delta_type import DocumentDeltaType
    from .dynamic_agent_config import DynamicAgentConfig
    from .dynamic_agent_config_type import DynamicAgentConfigType
    from .empty import Empty
    from .environment_config import EnvironmentConfig
    from .environment_config_network import EnvironmentConfigNetwork
    from .environment_config_network_one import EnvironmentConfigNetworkOne
    from .environment_config_type import EnvironmentConfigType
    from .environment_network_egress_allowlist import EnvironmentNetworkEgressAllowlist
    from .environment_network_egress_allowlist_allowlist import EnvironmentNetworkEgressAllowlistAllowlist
    from .environment_network_egress_allowlist_one import EnvironmentNetworkEgressAllowlistOne
    from .environment_source import EnvironmentSource
    from .environment_source_type import EnvironmentSourceType
    from .error import Error
    from .error_event import ErrorEvent
    from .error_event_event_type import ErrorEventEventType
    from .file_citation import FileCitation
    from .file_citation_type import FileCitationType
    from .file_search import FileSearch
    from .file_search_call_delta import FileSearchCallDelta
    from .file_search_call_delta_type import FileSearchCallDeltaType
    from .file_search_call_step import FileSearchCallStep
    from .file_search_call_step_type import FileSearchCallStepType
    from .file_search_result import FileSearchResult
    from .file_search_result_delta import FileSearchResultDelta
    from .file_search_result_delta_type import FileSearchResultDeltaType
    from .file_search_result_step import FileSearchResultStep
    from .file_search_result_step_type import FileSearchResultStepType
    from .file_search_type import FileSearchType
    from .function import Function
    from .function_call_delta import FunctionCallDelta
    from .function_call_delta_type import FunctionCallDeltaType
    from .function_call_step import FunctionCallStep
    from .function_call_step_type import FunctionCallStepType
    from .function_result_delta import FunctionResultDelta
    from .function_result_delta_result import FunctionResultDeltaResult
    from .function_result_delta_type import FunctionResultDeltaType
    from .function_result_step import FunctionResultStep
    from .function_result_step_result import FunctionResultStepResult
    from .function_result_step_type import FunctionResultStepType
    from .function_result_subcontent import FunctionResultSubcontent
    from .function_type import FunctionType
    from .generation_config import GenerationConfig
    from .generation_config_tool_choice import GenerationConfigToolChoice
    from .google_maps import GoogleMaps
    from .google_maps_call_arguments import GoogleMapsCallArguments
    from .google_maps_call_delta import GoogleMapsCallDelta
    from .google_maps_call_delta_type import GoogleMapsCallDeltaType
    from .google_maps_call_step import GoogleMapsCallStep
    from .google_maps_call_step_arguments import GoogleMapsCallStepArguments
    from .google_maps_call_step_type import GoogleMapsCallStepType
    from .google_maps_result import GoogleMapsResult
    from .google_maps_result_delta import GoogleMapsResultDelta
    from .google_maps_result_delta_type import GoogleMapsResultDeltaType
    from .google_maps_result_item import GoogleMapsResultItem
    from .google_maps_result_places import GoogleMapsResultPlaces
    from .google_maps_result_step import GoogleMapsResultStep
    from .google_maps_result_step_type import GoogleMapsResultStepType
    from .google_maps_type import GoogleMapsType
    from .google_search import GoogleSearch
    from .google_search_call_arguments import GoogleSearchCallArguments
    from .google_search_call_delta import GoogleSearchCallDelta
    from .google_search_call_delta_type import GoogleSearchCallDeltaType
    from .google_search_call_step import GoogleSearchCallStep
    from .google_search_call_step_arguments import GoogleSearchCallStepArguments
    from .google_search_call_step_search_type import GoogleSearchCallStepSearchType
    from .google_search_call_step_type import GoogleSearchCallStepType
    from .google_search_result import GoogleSearchResult
    from .google_search_result_delta import GoogleSearchResultDelta
    from .google_search_result_delta_type import GoogleSearchResultDeltaType
    from .google_search_result_item import GoogleSearchResultItem
    from .google_search_result_step import GoogleSearchResultStep
    from .google_search_result_step_type import GoogleSearchResultStepType
    from .google_search_search_types_item import GoogleSearchSearchTypesItem
    from .google_search_type import GoogleSearchType
    from .grounding_tool_count import GroundingToolCount
    from .grounding_tool_count_type import GroundingToolCountType
    from .image_config import ImageConfig
    from .image_config_aspect_ratio import ImageConfigAspectRatio
    from .image_config_image_size import ImageConfigImageSize
    from .image_content import ImageContent
    from .image_content_mime_type import ImageContentMimeType
    from .image_content_type import ImageContentType
    from .image_delta import ImageDelta
    from .image_delta_mime_type import ImageDeltaMimeType
    from .image_delta_type import ImageDeltaType
    from .image_response_format import ImageResponseFormat
    from .image_response_format_aspect_ratio import ImageResponseFormatAspectRatio
    from .image_response_format_delivery import ImageResponseFormatDelivery
    from .image_response_format_image_size import ImageResponseFormatImageSize
    from .image_response_format_mime_type import ImageResponseFormatMimeType
    from .image_response_format_type import ImageResponseFormatType
    from .interaction import Interaction
    from .interaction_agent_config import InteractionAgentConfig
    from .interaction_completed_event import InteractionCompletedEvent
    from .interaction_completed_event_event_type import InteractionCompletedEventEventType
    from .interaction_created_event import InteractionCreatedEvent
    from .interaction_created_event_event_type import InteractionCreatedEventEventType
    from .interaction_environment import InteractionEnvironment
    from .interaction_response_format import InteractionResponseFormat
    from .interaction_sse_event import InteractionSseEvent
    from .interaction_status import InteractionStatus
    from .interaction_status_update import InteractionStatusUpdate
    from .interaction_status_update_event_type import InteractionStatusUpdateEventType
    from .interaction_status_update_status import InteractionStatusUpdateStatus
    from .interactions_input import InteractionsInput
    from .list_agents_response import ListAgentsResponse
    from .list_webhooks_response import ListWebhooksResponse
    from .mcp_server import McpServer
    from .mcp_server_tool_call_delta import McpServerToolCallDelta
    from .mcp_server_tool_call_delta_type import McpServerToolCallDeltaType
    from .mcp_server_tool_call_step import McpServerToolCallStep
    from .mcp_server_tool_call_step_type import McpServerToolCallStepType
    from .mcp_server_tool_result_delta import McpServerToolResultDelta
    from .mcp_server_tool_result_delta_result import McpServerToolResultDeltaResult
    from .mcp_server_tool_result_delta_type import McpServerToolResultDeltaType
    from .mcp_server_tool_result_step import McpServerToolResultStep
    from .mcp_server_tool_result_step_result import McpServerToolResultStepResult
    from .mcp_server_tool_result_step_type import McpServerToolResultStepType
    from .mcp_server_type import McpServerType
    from .media_resolution import MediaResolution
    from .modality_tokens import ModalityTokens
    from .model_option import ModelOption
    from .model_option_eight import ModelOptionEight
    from .model_option_eighteen import ModelOptionEighteen
    from .model_option_eleven import ModelOptionEleven
    from .model_option_fifteen import ModelOptionFifteen
    from .model_option_five import ModelOptionFive
    from .model_option_four import ModelOptionFour
    from .model_option_fourteen import ModelOptionFourteen
    from .model_option_nine import ModelOptionNine
    from .model_option_nineteen import ModelOptionNineteen
    from .model_option_one import ModelOptionOne
    from .model_option_seven import ModelOptionSeven
    from .model_option_seventeen import ModelOptionSeventeen
    from .model_option_six import ModelOptionSix
    from .model_option_sixteen import ModelOptionSixteen
    from .model_option_ten import ModelOptionTen
    from .model_option_thirteen import ModelOptionThirteen
    from .model_option_three import ModelOptionThree
    from .model_option_twelve import ModelOptionTwelve
    from .model_option_twenty import ModelOptionTwenty
    from .model_option_two import ModelOptionTwo
    from .model_output_step import ModelOutputStep
    from .model_output_step_type import ModelOutputStepType
    from .ping_webhook_request import PingWebhookRequest
    from .ping_webhook_response import PingWebhookResponse
    from .place_citation import PlaceCitation
    from .place_citation_type import PlaceCitationType
    from .places import Places
    from .response_format import ResponseFormat
    from .response_format_list import ResponseFormatList
    from .response_modality import ResponseModality
    from .retrieval import Retrieval
    from .retrieval_retrieval_types_item import RetrievalRetrievalTypesItem
    from .retrieval_type import RetrievalType
    from .review_snippet import ReviewSnippet
    from .rotate_signing_secret_response import RotateSigningSecretResponse
    from .service_tier import ServiceTier
    from .signing_secret import SigningSecret
    from .signing_secret_read import SigningSecretRead
    from .source import Source
    from .source_type import SourceType
    from .speech_config import SpeechConfig
    from .step import Step
    from .step_delta import StepDelta
    from .step_delta_data import StepDeltaData
    from .step_delta_event_type import StepDeltaEventType
    from .step_start import StepStart
    from .step_start_event_type import StepStartEventType
    from .step_stop import StepStop
    from .step_stop_event_type import StepStopEventType
    from .text_annotation_delta import TextAnnotationDelta
    from .text_annotation_delta_type import TextAnnotationDeltaType
    from .text_content import TextContent
    from .text_content_type import TextContentType
    from .text_delta import TextDelta
    from .text_delta_type import TextDeltaType
    from .text_response_format import TextResponseFormat
    from .text_response_format_mime_type import TextResponseFormatMimeType
    from .text_response_format_type import TextResponseFormatType
    from .thinking_level import ThinkingLevel
    from .thinking_summaries import ThinkingSummaries
    from .thought_content import ThoughtContent
    from .thought_content_type import ThoughtContentType
    from .thought_signature_delta import ThoughtSignatureDelta
    from .thought_signature_delta_type import ThoughtSignatureDeltaType
    from .thought_step import ThoughtStep
    from .thought_step_type import ThoughtStepType
    from .thought_summary_content import ThoughtSummaryContent
    from .thought_summary_delta import ThoughtSummaryDelta
    from .thought_summary_delta_type import ThoughtSummaryDeltaType
    from .tool import Tool
    from .tool_choice_config import ToolChoiceConfig
    from .tool_choice_type import ToolChoiceType
    from .turn import Turn
    from .turn_content import TurnContent
    from .url_citation import UrlCitation
    from .url_citation_type import UrlCitationType
    from .url_context import UrlContext
    from .url_context_call_arguments import UrlContextCallArguments
    from .url_context_call_delta import UrlContextCallDelta
    from .url_context_call_delta_type import UrlContextCallDeltaType
    from .url_context_call_step import UrlContextCallStep
    from .url_context_call_step_arguments import UrlContextCallStepArguments
    from .url_context_call_step_type import UrlContextCallStepType
    from .url_context_result import UrlContextResult
    from .url_context_result_delta import UrlContextResultDelta
    from .url_context_result_delta_type import UrlContextResultDeltaType
    from .url_context_result_item import UrlContextResultItem
    from .url_context_result_item_status import UrlContextResultItemStatus
    from .url_context_result_status import UrlContextResultStatus
    from .url_context_result_step import UrlContextResultStep
    from .url_context_result_step_type import UrlContextResultStepType
    from .url_context_type import UrlContextType
    from .usage import Usage
    from .user_input_step import UserInputStep
    from .user_input_step_type import UserInputStepType
    from .vertex_ai_search_config import VertexAiSearchConfig
    from .video_content import VideoContent
    from .video_content_mime_type import VideoContentMimeType
    from .video_content_type import VideoContentType
    from .video_delta import VideoDelta
    from .video_delta_mime_type import VideoDeltaMimeType
    from .video_delta_type import VideoDeltaType
    from .webhook import Webhook
    from .webhook_config import WebhookConfig
    from .webhook_read import WebhookRead
    from .webhook_state import WebhookState
    from .webhook_subscribed_events_item import WebhookSubscribedEventsItem
    from .webhook_subscribed_events_item_five import WebhookSubscribedEventsItemFive
    from .webhook_subscribed_events_item_four import WebhookSubscribedEventsItemFour
    from .webhook_subscribed_events_item_one import WebhookSubscribedEventsItemOne
    from .webhook_subscribed_events_item_seven import WebhookSubscribedEventsItemSeven
    from .webhook_subscribed_events_item_six import WebhookSubscribedEventsItemSix
    from .webhook_subscribed_events_item_three import WebhookSubscribedEventsItemThree
    from .webhook_subscribed_events_item_two import WebhookSubscribedEventsItemTwo
_dynamic_imports: typing.Dict[str, str] = {
    "Agent": ".agent",
    "AgentBaseEnvironment": ".agent_base_environment",
    "AgentEgressAllowlist": ".agent_egress_allowlist",
    "AgentEgressRule": ".agent_egress_rule",
    "AgentOption": ".agent_option",
    "AgentOptionOne": ".agent_option_one",
    "AgentOptionThree": ".agent_option_three",
    "AgentOptionTwo": ".agent_option_two",
    "AgentTool": ".agent_tool",
    "AllowedTools": ".allowed_tools",
    "AllowlistEntry": ".allowlist_entry",
    "Annotation": ".annotation",
    "ArgumentsDelta": ".arguments_delta",
    "ArgumentsDeltaType": ".arguments_delta_type",
    "AudioContent": ".audio_content",
    "AudioContentMimeType": ".audio_content_mime_type",
    "AudioContentType": ".audio_content_type",
    "AudioDelta": ".audio_delta",
    "AudioDeltaMimeType": ".audio_delta_mime_type",
    "AudioDeltaType": ".audio_delta_type",
    "AudioResponseFormat": ".audio_response_format",
    "AudioResponseFormatDelivery": ".audio_response_format_delivery",
    "AudioResponseFormatMimeType": ".audio_response_format_mime_type",
    "AudioResponseFormatType": ".audio_response_format_type",
    "CodeExecution": ".code_execution",
    "CodeExecutionCallArguments": ".code_execution_call_arguments",
    "CodeExecutionCallArgumentsLanguage": ".code_execution_call_arguments_language",
    "CodeExecutionCallDelta": ".code_execution_call_delta",
    "CodeExecutionCallDeltaType": ".code_execution_call_delta_type",
    "CodeExecutionCallStep": ".code_execution_call_step",
    "CodeExecutionCallStepArguments": ".code_execution_call_step_arguments",
    "CodeExecutionCallStepArgumentsLanguage": ".code_execution_call_step_arguments_language",
    "CodeExecutionCallStepType": ".code_execution_call_step_type",
    "CodeExecutionResultDelta": ".code_execution_result_delta",
    "CodeExecutionResultDeltaType": ".code_execution_result_delta_type",
    "CodeExecutionResultStep": ".code_execution_result_step",
    "CodeExecutionResultStepType": ".code_execution_result_step_type",
    "CodeExecutionType": ".code_execution_type",
    "ComputerUse": ".computer_use",
    "ComputerUseEnvironment": ".computer_use_environment",
    "ComputerUseType": ".computer_use_type",
    "Content": ".content",
    "ContentDelta": ".content_delta",
    "ContentDeltaData": ".content_delta_data",
    "ContentDeltaEventType": ".content_delta_event_type",
    "ContentStart": ".content_start",
    "ContentStartEventType": ".content_start_event_type",
    "ContentStop": ".content_stop",
    "ContentStopEventType": ".content_stop_event_type",
    "CreateAgentInteractionParams": ".create_agent_interaction_params",
    "CreateAgentInteractionParamsAgentConfig": ".create_agent_interaction_params_agent_config",
    "CreateAgentInteractionParamsEnvironment": ".create_agent_interaction_params_environment",
    "CreateAgentInteractionParamsResponseFormat": ".create_agent_interaction_params_response_format",
    "CreateModelInteractionParams": ".create_model_interaction_params",
    "CreateModelInteractionParamsEnvironment": ".create_model_interaction_params_environment",
    "CreateModelInteractionParamsResponseFormat": ".create_model_interaction_params_response_format",
    "DeepResearchAgentConfig": ".deep_research_agent_config",
    "DeepResearchAgentConfigType": ".deep_research_agent_config_type",
    "DeepResearchAgentConfigVisualization": ".deep_research_agent_config_visualization",
    "DocumentContent": ".document_content",
    "DocumentContentMimeType": ".document_content_mime_type",
    "DocumentContentType": ".document_content_type",
    "DocumentDelta": ".document_delta",
    "DocumentDeltaMimeType": ".document_delta_mime_type",
    "DocumentDeltaType": ".document_delta_type",
    "DynamicAgentConfig": ".dynamic_agent_config",
    "DynamicAgentConfigType": ".dynamic_agent_config_type",
    "Empty": ".empty",
    "EnvironmentConfig": ".environment_config",
    "EnvironmentConfigNetwork": ".environment_config_network",
    "EnvironmentConfigNetworkOne": ".environment_config_network_one",
    "EnvironmentConfigType": ".environment_config_type",
    "EnvironmentNetworkEgressAllowlist": ".environment_network_egress_allowlist",
    "EnvironmentNetworkEgressAllowlistAllowlist": ".environment_network_egress_allowlist_allowlist",
    "EnvironmentNetworkEgressAllowlistOne": ".environment_network_egress_allowlist_one",
    "EnvironmentSource": ".environment_source",
    "EnvironmentSourceType": ".environment_source_type",
    "Error": ".error",
    "ErrorEvent": ".error_event",
    "ErrorEventEventType": ".error_event_event_type",
    "FileCitation": ".file_citation",
    "FileCitationType": ".file_citation_type",
    "FileSearch": ".file_search",
    "FileSearchCallDelta": ".file_search_call_delta",
    "FileSearchCallDeltaType": ".file_search_call_delta_type",
    "FileSearchCallStep": ".file_search_call_step",
    "FileSearchCallStepType": ".file_search_call_step_type",
    "FileSearchResult": ".file_search_result",
    "FileSearchResultDelta": ".file_search_result_delta",
    "FileSearchResultDeltaType": ".file_search_result_delta_type",
    "FileSearchResultStep": ".file_search_result_step",
    "FileSearchResultStepType": ".file_search_result_step_type",
    "FileSearchType": ".file_search_type",
    "Function": ".function",
    "FunctionCallDelta": ".function_call_delta",
    "FunctionCallDeltaType": ".function_call_delta_type",
    "FunctionCallStep": ".function_call_step",
    "FunctionCallStepType": ".function_call_step_type",
    "FunctionResultDelta": ".function_result_delta",
    "FunctionResultDeltaResult": ".function_result_delta_result",
    "FunctionResultDeltaType": ".function_result_delta_type",
    "FunctionResultStep": ".function_result_step",
    "FunctionResultStepResult": ".function_result_step_result",
    "FunctionResultStepType": ".function_result_step_type",
    "FunctionResultSubcontent": ".function_result_subcontent",
    "FunctionType": ".function_type",
    "GenerationConfig": ".generation_config",
    "GenerationConfigToolChoice": ".generation_config_tool_choice",
    "GoogleMaps": ".google_maps",
    "GoogleMapsCallArguments": ".google_maps_call_arguments",
    "GoogleMapsCallDelta": ".google_maps_call_delta",
    "GoogleMapsCallDeltaType": ".google_maps_call_delta_type",
    "GoogleMapsCallStep": ".google_maps_call_step",
    "GoogleMapsCallStepArguments": ".google_maps_call_step_arguments",
    "GoogleMapsCallStepType": ".google_maps_call_step_type",
    "GoogleMapsResult": ".google_maps_result",
    "GoogleMapsResultDelta": ".google_maps_result_delta",
    "GoogleMapsResultDeltaType": ".google_maps_result_delta_type",
    "GoogleMapsResultItem": ".google_maps_result_item",
    "GoogleMapsResultPlaces": ".google_maps_result_places",
    "GoogleMapsResultStep": ".google_maps_result_step",
    "GoogleMapsResultStepType": ".google_maps_result_step_type",
    "GoogleMapsType": ".google_maps_type",
    "GoogleSearch": ".google_search",
    "GoogleSearchCallArguments": ".google_search_call_arguments",
    "GoogleSearchCallDelta": ".google_search_call_delta",
    "GoogleSearchCallDeltaType": ".google_search_call_delta_type",
    "GoogleSearchCallStep": ".google_search_call_step",
    "GoogleSearchCallStepArguments": ".google_search_call_step_arguments",
    "GoogleSearchCallStepSearchType": ".google_search_call_step_search_type",
    "GoogleSearchCallStepType": ".google_search_call_step_type",
    "GoogleSearchResult": ".google_search_result",
    "GoogleSearchResultDelta": ".google_search_result_delta",
    "GoogleSearchResultDeltaType": ".google_search_result_delta_type",
    "GoogleSearchResultItem": ".google_search_result_item",
    "GoogleSearchResultStep": ".google_search_result_step",
    "GoogleSearchResultStepType": ".google_search_result_step_type",
    "GoogleSearchSearchTypesItem": ".google_search_search_types_item",
    "GoogleSearchType": ".google_search_type",
    "GroundingToolCount": ".grounding_tool_count",
    "GroundingToolCountType": ".grounding_tool_count_type",
    "ImageConfig": ".image_config",
    "ImageConfigAspectRatio": ".image_config_aspect_ratio",
    "ImageConfigImageSize": ".image_config_image_size",
    "ImageContent": ".image_content",
    "ImageContentMimeType": ".image_content_mime_type",
    "ImageContentType": ".image_content_type",
    "ImageDelta": ".image_delta",
    "ImageDeltaMimeType": ".image_delta_mime_type",
    "ImageDeltaType": ".image_delta_type",
    "ImageResponseFormat": ".image_response_format",
    "ImageResponseFormatAspectRatio": ".image_response_format_aspect_ratio",
    "ImageResponseFormatDelivery": ".image_response_format_delivery",
    "ImageResponseFormatImageSize": ".image_response_format_image_size",
    "ImageResponseFormatMimeType": ".image_response_format_mime_type",
    "ImageResponseFormatType": ".image_response_format_type",
    "Interaction": ".interaction",
    "InteractionAgentConfig": ".interaction_agent_config",
    "InteractionCompletedEvent": ".interaction_completed_event",
    "InteractionCompletedEventEventType": ".interaction_completed_event_event_type",
    "InteractionCreatedEvent": ".interaction_created_event",
    "InteractionCreatedEventEventType": ".interaction_created_event_event_type",
    "InteractionEnvironment": ".interaction_environment",
    "InteractionResponseFormat": ".interaction_response_format",
    "InteractionSseEvent": ".interaction_sse_event",
    "InteractionStatus": ".interaction_status",
    "InteractionStatusUpdate": ".interaction_status_update",
    "InteractionStatusUpdateEventType": ".interaction_status_update_event_type",
    "InteractionStatusUpdateStatus": ".interaction_status_update_status",
    "InteractionsInput": ".interactions_input",
    "ListAgentsResponse": ".list_agents_response",
    "ListWebhooksResponse": ".list_webhooks_response",
    "McpServer": ".mcp_server",
    "McpServerToolCallDelta": ".mcp_server_tool_call_delta",
    "McpServerToolCallDeltaType": ".mcp_server_tool_call_delta_type",
    "McpServerToolCallStep": ".mcp_server_tool_call_step",
    "McpServerToolCallStepType": ".mcp_server_tool_call_step_type",
    "McpServerToolResultDelta": ".mcp_server_tool_result_delta",
    "McpServerToolResultDeltaResult": ".mcp_server_tool_result_delta_result",
    "McpServerToolResultDeltaType": ".mcp_server_tool_result_delta_type",
    "McpServerToolResultStep": ".mcp_server_tool_result_step",
    "McpServerToolResultStepResult": ".mcp_server_tool_result_step_result",
    "McpServerToolResultStepType": ".mcp_server_tool_result_step_type",
    "McpServerType": ".mcp_server_type",
    "MediaResolution": ".media_resolution",
    "ModalityTokens": ".modality_tokens",
    "ModelOption": ".model_option",
    "ModelOptionEight": ".model_option_eight",
    "ModelOptionEighteen": ".model_option_eighteen",
    "ModelOptionEleven": ".model_option_eleven",
    "ModelOptionFifteen": ".model_option_fifteen",
    "ModelOptionFive": ".model_option_five",
    "ModelOptionFour": ".model_option_four",
    "ModelOptionFourteen": ".model_option_fourteen",
    "ModelOptionNine": ".model_option_nine",
    "ModelOptionNineteen": ".model_option_nineteen",
    "ModelOptionOne": ".model_option_one",
    "ModelOptionSeven": ".model_option_seven",
    "ModelOptionSeventeen": ".model_option_seventeen",
    "ModelOptionSix": ".model_option_six",
    "ModelOptionSixteen": ".model_option_sixteen",
    "ModelOptionTen": ".model_option_ten",
    "ModelOptionThirteen": ".model_option_thirteen",
    "ModelOptionThree": ".model_option_three",
    "ModelOptionTwelve": ".model_option_twelve",
    "ModelOptionTwenty": ".model_option_twenty",
    "ModelOptionTwo": ".model_option_two",
    "ModelOutputStep": ".model_output_step",
    "ModelOutputStepType": ".model_output_step_type",
    "PingWebhookRequest": ".ping_webhook_request",
    "PingWebhookResponse": ".ping_webhook_response",
    "PlaceCitation": ".place_citation",
    "PlaceCitationType": ".place_citation_type",
    "Places": ".places",
    "ResponseFormat": ".response_format",
    "ResponseFormatList": ".response_format_list",
    "ResponseModality": ".response_modality",
    "Retrieval": ".retrieval",
    "RetrievalRetrievalTypesItem": ".retrieval_retrieval_types_item",
    "RetrievalType": ".retrieval_type",
    "ReviewSnippet": ".review_snippet",
    "RotateSigningSecretResponse": ".rotate_signing_secret_response",
    "ServiceTier": ".service_tier",
    "SigningSecret": ".signing_secret",
    "SigningSecretRead": ".signing_secret_read",
    "Source": ".source",
    "SourceType": ".source_type",
    "SpeechConfig": ".speech_config",
    "Step": ".step",
    "StepDelta": ".step_delta",
    "StepDeltaData": ".step_delta_data",
    "StepDeltaEventType": ".step_delta_event_type",
    "StepStart": ".step_start",
    "StepStartEventType": ".step_start_event_type",
    "StepStop": ".step_stop",
    "StepStopEventType": ".step_stop_event_type",
    "TextAnnotationDelta": ".text_annotation_delta",
    "TextAnnotationDeltaType": ".text_annotation_delta_type",
    "TextContent": ".text_content",
    "TextContentType": ".text_content_type",
    "TextDelta": ".text_delta",
    "TextDeltaType": ".text_delta_type",
    "TextResponseFormat": ".text_response_format",
    "TextResponseFormatMimeType": ".text_response_format_mime_type",
    "TextResponseFormatType": ".text_response_format_type",
    "ThinkingLevel": ".thinking_level",
    "ThinkingSummaries": ".thinking_summaries",
    "ThoughtContent": ".thought_content",
    "ThoughtContentType": ".thought_content_type",
    "ThoughtSignatureDelta": ".thought_signature_delta",
    "ThoughtSignatureDeltaType": ".thought_signature_delta_type",
    "ThoughtStep": ".thought_step",
    "ThoughtStepType": ".thought_step_type",
    "ThoughtSummaryContent": ".thought_summary_content",
    "ThoughtSummaryDelta": ".thought_summary_delta",
    "ThoughtSummaryDeltaType": ".thought_summary_delta_type",
    "Tool": ".tool",
    "ToolChoiceConfig": ".tool_choice_config",
    "ToolChoiceType": ".tool_choice_type",
    "Turn": ".turn",
    "TurnContent": ".turn_content",
    "UrlCitation": ".url_citation",
    "UrlCitationType": ".url_citation_type",
    "UrlContext": ".url_context",
    "UrlContextCallArguments": ".url_context_call_arguments",
    "UrlContextCallDelta": ".url_context_call_delta",
    "UrlContextCallDeltaType": ".url_context_call_delta_type",
    "UrlContextCallStep": ".url_context_call_step",
    "UrlContextCallStepArguments": ".url_context_call_step_arguments",
    "UrlContextCallStepType": ".url_context_call_step_type",
    "UrlContextResult": ".url_context_result",
    "UrlContextResultDelta": ".url_context_result_delta",
    "UrlContextResultDeltaType": ".url_context_result_delta_type",
    "UrlContextResultItem": ".url_context_result_item",
    "UrlContextResultItemStatus": ".url_context_result_item_status",
    "UrlContextResultStatus": ".url_context_result_status",
    "UrlContextResultStep": ".url_context_result_step",
    "UrlContextResultStepType": ".url_context_result_step_type",
    "UrlContextType": ".url_context_type",
    "Usage": ".usage",
    "UserInputStep": ".user_input_step",
    "UserInputStepType": ".user_input_step_type",
    "VertexAiSearchConfig": ".vertex_ai_search_config",
    "VideoContent": ".video_content",
    "VideoContentMimeType": ".video_content_mime_type",
    "VideoContentType": ".video_content_type",
    "VideoDelta": ".video_delta",
    "VideoDeltaMimeType": ".video_delta_mime_type",
    "VideoDeltaType": ".video_delta_type",
    "Webhook": ".webhook",
    "WebhookConfig": ".webhook_config",
    "WebhookRead": ".webhook_read",
    "WebhookState": ".webhook_state",
    "WebhookSubscribedEventsItem": ".webhook_subscribed_events_item",
    "WebhookSubscribedEventsItemFive": ".webhook_subscribed_events_item_five",
    "WebhookSubscribedEventsItemFour": ".webhook_subscribed_events_item_four",
    "WebhookSubscribedEventsItemOne": ".webhook_subscribed_events_item_one",
    "WebhookSubscribedEventsItemSeven": ".webhook_subscribed_events_item_seven",
    "WebhookSubscribedEventsItemSix": ".webhook_subscribed_events_item_six",
    "WebhookSubscribedEventsItemThree": ".webhook_subscribed_events_item_three",
    "WebhookSubscribedEventsItemTwo": ".webhook_subscribed_events_item_two",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Agent",
    "AgentBaseEnvironment",
    "AgentEgressAllowlist",
    "AgentEgressRule",
    "AgentOption",
    "AgentOptionOne",
    "AgentOptionThree",
    "AgentOptionTwo",
    "AgentTool",
    "AllowedTools",
    "AllowlistEntry",
    "Annotation",
    "ArgumentsDelta",
    "ArgumentsDeltaType",
    "AudioContent",
    "AudioContentMimeType",
    "AudioContentType",
    "AudioDelta",
    "AudioDeltaMimeType",
    "AudioDeltaType",
    "AudioResponseFormat",
    "AudioResponseFormatDelivery",
    "AudioResponseFormatMimeType",
    "AudioResponseFormatType",
    "CodeExecution",
    "CodeExecutionCallArguments",
    "CodeExecutionCallArgumentsLanguage",
    "CodeExecutionCallDelta",
    "CodeExecutionCallDeltaType",
    "CodeExecutionCallStep",
    "CodeExecutionCallStepArguments",
    "CodeExecutionCallStepArgumentsLanguage",
    "CodeExecutionCallStepType",
    "CodeExecutionResultDelta",
    "CodeExecutionResultDeltaType",
    "CodeExecutionResultStep",
    "CodeExecutionResultStepType",
    "CodeExecutionType",
    "ComputerUse",
    "ComputerUseEnvironment",
    "ComputerUseType",
    "Content",
    "ContentDelta",
    "ContentDeltaData",
    "ContentDeltaEventType",
    "ContentStart",
    "ContentStartEventType",
    "ContentStop",
    "ContentStopEventType",
    "CreateAgentInteractionParams",
    "CreateAgentInteractionParamsAgentConfig",
    "CreateAgentInteractionParamsEnvironment",
    "CreateAgentInteractionParamsResponseFormat",
    "CreateModelInteractionParams",
    "CreateModelInteractionParamsEnvironment",
    "CreateModelInteractionParamsResponseFormat",
    "DeepResearchAgentConfig",
    "DeepResearchAgentConfigType",
    "DeepResearchAgentConfigVisualization",
    "DocumentContent",
    "DocumentContentMimeType",
    "DocumentContentType",
    "DocumentDelta",
    "DocumentDeltaMimeType",
    "DocumentDeltaType",
    "DynamicAgentConfig",
    "DynamicAgentConfigType",
    "Empty",
    "EnvironmentConfig",
    "EnvironmentConfigNetwork",
    "EnvironmentConfigNetworkOne",
    "EnvironmentConfigType",
    "EnvironmentNetworkEgressAllowlist",
    "EnvironmentNetworkEgressAllowlistAllowlist",
    "EnvironmentNetworkEgressAllowlistOne",
    "EnvironmentSource",
    "EnvironmentSourceType",
    "Error",
    "ErrorEvent",
    "ErrorEventEventType",
    "FileCitation",
    "FileCitationType",
    "FileSearch",
    "FileSearchCallDelta",
    "FileSearchCallDeltaType",
    "FileSearchCallStep",
    "FileSearchCallStepType",
    "FileSearchResult",
    "FileSearchResultDelta",
    "FileSearchResultDeltaType",
    "FileSearchResultStep",
    "FileSearchResultStepType",
    "FileSearchType",
    "Function",
    "FunctionCallDelta",
    "FunctionCallDeltaType",
    "FunctionCallStep",
    "FunctionCallStepType",
    "FunctionResultDelta",
    "FunctionResultDeltaResult",
    "FunctionResultDeltaType",
    "FunctionResultStep",
    "FunctionResultStepResult",
    "FunctionResultStepType",
    "FunctionResultSubcontent",
    "FunctionType",
    "GenerationConfig",
    "GenerationConfigToolChoice",
    "GoogleMaps",
    "GoogleMapsCallArguments",
    "GoogleMapsCallDelta",
    "GoogleMapsCallDeltaType",
    "GoogleMapsCallStep",
    "GoogleMapsCallStepArguments",
    "GoogleMapsCallStepType",
    "GoogleMapsResult",
    "GoogleMapsResultDelta",
    "GoogleMapsResultDeltaType",
    "GoogleMapsResultItem",
    "GoogleMapsResultPlaces",
    "GoogleMapsResultStep",
    "GoogleMapsResultStepType",
    "GoogleMapsType",
    "GoogleSearch",
    "GoogleSearchCallArguments",
    "GoogleSearchCallDelta",
    "GoogleSearchCallDeltaType",
    "GoogleSearchCallStep",
    "GoogleSearchCallStepArguments",
    "GoogleSearchCallStepSearchType",
    "GoogleSearchCallStepType",
    "GoogleSearchResult",
    "GoogleSearchResultDelta",
    "GoogleSearchResultDeltaType",
    "GoogleSearchResultItem",
    "GoogleSearchResultStep",
    "GoogleSearchResultStepType",
    "GoogleSearchSearchTypesItem",
    "GoogleSearchType",
    "GroundingToolCount",
    "GroundingToolCountType",
    "ImageConfig",
    "ImageConfigAspectRatio",
    "ImageConfigImageSize",
    "ImageContent",
    "ImageContentMimeType",
    "ImageContentType",
    "ImageDelta",
    "ImageDeltaMimeType",
    "ImageDeltaType",
    "ImageResponseFormat",
    "ImageResponseFormatAspectRatio",
    "ImageResponseFormatDelivery",
    "ImageResponseFormatImageSize",
    "ImageResponseFormatMimeType",
    "ImageResponseFormatType",
    "Interaction",
    "InteractionAgentConfig",
    "InteractionCompletedEvent",
    "InteractionCompletedEventEventType",
    "InteractionCreatedEvent",
    "InteractionCreatedEventEventType",
    "InteractionEnvironment",
    "InteractionResponseFormat",
    "InteractionSseEvent",
    "InteractionStatus",
    "InteractionStatusUpdate",
    "InteractionStatusUpdateEventType",
    "InteractionStatusUpdateStatus",
    "InteractionsInput",
    "ListAgentsResponse",
    "ListWebhooksResponse",
    "McpServer",
    "McpServerToolCallDelta",
    "McpServerToolCallDeltaType",
    "McpServerToolCallStep",
    "McpServerToolCallStepType",
    "McpServerToolResultDelta",
    "McpServerToolResultDeltaResult",
    "McpServerToolResultDeltaType",
    "McpServerToolResultStep",
    "McpServerToolResultStepResult",
    "McpServerToolResultStepType",
    "McpServerType",
    "MediaResolution",
    "ModalityTokens",
    "ModelOption",
    "ModelOptionEight",
    "ModelOptionEighteen",
    "ModelOptionEleven",
    "ModelOptionFifteen",
    "ModelOptionFive",
    "ModelOptionFour",
    "ModelOptionFourteen",
    "ModelOptionNine",
    "ModelOptionNineteen",
    "ModelOptionOne",
    "ModelOptionSeven",
    "ModelOptionSeventeen",
    "ModelOptionSix",
    "ModelOptionSixteen",
    "ModelOptionTen",
    "ModelOptionThirteen",
    "ModelOptionThree",
    "ModelOptionTwelve",
    "ModelOptionTwenty",
    "ModelOptionTwo",
    "ModelOutputStep",
    "ModelOutputStepType",
    "PingWebhookRequest",
    "PingWebhookResponse",
    "PlaceCitation",
    "PlaceCitationType",
    "Places",
    "ResponseFormat",
    "ResponseFormatList",
    "ResponseModality",
    "Retrieval",
    "RetrievalRetrievalTypesItem",
    "RetrievalType",
    "ReviewSnippet",
    "RotateSigningSecretResponse",
    "ServiceTier",
    "SigningSecret",
    "SigningSecretRead",
    "Source",
    "SourceType",
    "SpeechConfig",
    "Step",
    "StepDelta",
    "StepDeltaData",
    "StepDeltaEventType",
    "StepStart",
    "StepStartEventType",
    "StepStop",
    "StepStopEventType",
    "TextAnnotationDelta",
    "TextAnnotationDeltaType",
    "TextContent",
    "TextContentType",
    "TextDelta",
    "TextDeltaType",
    "TextResponseFormat",
    "TextResponseFormatMimeType",
    "TextResponseFormatType",
    "ThinkingLevel",
    "ThinkingSummaries",
    "ThoughtContent",
    "ThoughtContentType",
    "ThoughtSignatureDelta",
    "ThoughtSignatureDeltaType",
    "ThoughtStep",
    "ThoughtStepType",
    "ThoughtSummaryContent",
    "ThoughtSummaryDelta",
    "ThoughtSummaryDeltaType",
    "Tool",
    "ToolChoiceConfig",
    "ToolChoiceType",
    "Turn",
    "TurnContent",
    "UrlCitation",
    "UrlCitationType",
    "UrlContext",
    "UrlContextCallArguments",
    "UrlContextCallDelta",
    "UrlContextCallDeltaType",
    "UrlContextCallStep",
    "UrlContextCallStepArguments",
    "UrlContextCallStepType",
    "UrlContextResult",
    "UrlContextResultDelta",
    "UrlContextResultDeltaType",
    "UrlContextResultItem",
    "UrlContextResultItemStatus",
    "UrlContextResultStatus",
    "UrlContextResultStep",
    "UrlContextResultStepType",
    "UrlContextType",
    "Usage",
    "UserInputStep",
    "UserInputStepType",
    "VertexAiSearchConfig",
    "VideoContent",
    "VideoContentMimeType",
    "VideoContentType",
    "VideoDelta",
    "VideoDeltaMimeType",
    "VideoDeltaType",
    "Webhook",
    "WebhookConfig",
    "WebhookRead",
    "WebhookState",
    "WebhookSubscribedEventsItem",
    "WebhookSubscribedEventsItemFive",
    "WebhookSubscribedEventsItemFour",
    "WebhookSubscribedEventsItemOne",
    "WebhookSubscribedEventsItemSeven",
    "WebhookSubscribedEventsItemSix",
    "WebhookSubscribedEventsItemThree",
    "WebhookSubscribedEventsItemTwo",
]
