# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_egress_rule import AgentEgressRule


class AgentEgressAllowlist(UniversalBaseModel):
    """
    Network egress configuration for the environment.
    """

    allowlist: typing.Optional[typing.List[AgentEgressRule]] = pydantic.Field(default=None)
    """
    List of allowed domains and their configurations.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
