# This file was auto-generated by Fern from our API Definition.

import typing

from .code_execution import CodeExecution
from .google_search import GoogleSearch
from .mcp_server import McpServer
from .url_context import UrlContext

AgentTool = typing.Union[CodeExecution, GoogleSearch, UrlContext, McpServer]
