# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgentEgressRule(UniversalBaseModel):
    """
    A network egress rule that controls which external domains the
    environment is allowed to reach.  Each rule identifies a target domain
    and, optionally, a set of HTTP headers to inject into every matching
    outbound request.
    """

    domain: typing.Optional[str] = pydantic.Field(default=None)
    """
    The domain pattern to match for this rule.
    Use an exact hostname (e.g., `github.com`), a wildcard prefix
    (e.g., `*.googleapis.com`), or `*` to match all domains.
    """

    transform: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Headers to inject into requests matching this rule.
    Key: header name (e.g., "Authorization").
    Value: header value (e.g., "Bearer your-token").
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
