# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_option_one import AgentOptionOne
from .agent_option_three import AgentOptionThree
from .agent_option_two import AgentOptionTwo

AgentOption = typing.Union[str, AgentOptionOne, AgentOptionTwo, AgentOptionThree]
