# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_base_environment import AgentBaseEnvironment
from .agent_tool import AgentTool


class Agent(UniversalBaseModel):
    """
    An agent definition for the CreateAgent API.
    This message is the target for annotation-parser-based JSON parsing.
    New format:
      {
        "id": "customer-sentinel",
        "base_agent": "",
        "system_instruction": "...",
        "base_environment": { "type": "remote", "sources": [...] },
        "tools": [ {"type": "code_execution"} ]
      }
    """

    base_agent: typing.Optional[str] = pydantic.Field(default=None)
    """
    The base agent to extend.
    """

    base_environment: typing.Optional[AgentBaseEnvironment] = pydantic.Field(default=None)
    """
    The environment configuration for the agent.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent description for developers to quickly read and understand.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier for the agent.
    """

    system_instruction: typing.Optional[str] = pydantic.Field(default=None)
    """
    System instruction for the agent.
    """

    tools: typing.Optional[typing.List[AgentTool]] = pydantic.Field(default=None)
    """
    The tools available to the agent.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
