# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tool_choice_type import ToolChoiceType


class AllowedTools(UniversalBaseModel):
    """
    The configuration for allowed tools.
    """

    mode: typing.Optional[ToolChoiceType] = pydantic.Field(default=None)
    """
    The mode of the tool choice.
    """

    tools: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The names of the allowed tools.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
