# This file was auto-generated by Fern from our API Definition.

import typing

from .file_citation import FileCitation
from .place_citation import PlaceCitation
from .url_citation import UrlCitation

Annotation = typing.Union[UrlCitation, FileCitation, PlaceCitation]
