# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .audio_content_mime_type import AudioContentMimeType
from .audio_content_type import AudioContentType


class AudioContent(UniversalBaseModel):
    """
    An audio content block.
    """

    channels: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of audio channels.
    """

    data: typing.Optional[str] = pydantic.Field(default=None)
    """
    The audio content.
    """

    mime_type: typing.Optional[AudioContentMimeType] = pydantic.Field(default=None)
    """
    The mime type of the audio.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    The sample rate of the audio.
    """

    type: AudioContentType
    uri: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URI of the audio.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
