# This file was auto-generated by Fern from our API Definition.

import typing

AudioResponseFormatMimeType = typing.Union[
    typing.Literal["audio/mp3", "audio/ogg_opus", "audio/l16", "audio/wav", "audio/alaw", "audio/mulaw"], typing.Any
]
