# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .audio_delta_mime_type import AudioDeltaMimeType
from .audio_delta_type import AudioDeltaType


class AudioDelta(UniversalBaseModel):
    channels: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of audio channels.
    """

    data: typing.Optional[str] = None
    mime_type: typing.Optional[AudioDeltaMimeType] = None
    rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Deprecated. Use sample_rate instead. The value is ignored.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    The sample rate of the audio.
    """

    type: AudioDeltaType
    uri: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
