# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .audio_response_format_delivery import AudioResponseFormatDelivery
from .audio_response_format_mime_type import AudioResponseFormatMimeType
from .audio_response_format_type import AudioResponseFormatType


class AudioResponseFormat(UniversalBaseModel):
    """
    Configuration for audio output format.
    """

    bit_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Bit rate in bits per second (bps). Only applicable for compressed formats
    (MP3, Opus).
    """

    delivery: typing.Optional[AudioResponseFormatDelivery] = pydantic.Field(default=None)
    """
    The delivery mode for the audio output.
    """

    mime_type: typing.Optional[AudioResponseFormatMimeType] = pydantic.Field(default=None)
    """
    The MIME type of the audio output.
    """

    sample_rate: typing.Optional[int] = pydantic.Field(default=None)
    """
    Sample rate in Hz.
    """

    type: AudioResponseFormatType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
