# This file was auto-generated by Fern from our API Definition.

import typing

AudioDeltaMimeType = typing.Union[
    typing.Literal[
        "audio/wav",
        "audio/mp3",
        "audio/aiff",
        "audio/aac",
        "audio/ogg",
        "audio/flac",
        "audio/mpeg",
        "audio/m4a",
        "audio/l16",
        "audio/opus",
        "audio/alaw",
        "audio/mulaw",
    ],
    typing.Any,
]
