# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .code_execution_call_step_arguments import CodeExecutionCallStepArguments
from .code_execution_call_step_type import CodeExecutionCallStepType


class CodeExecutionCallStep(UniversalBaseModel):
    """
    Code execution call step.
    """

    arguments: CodeExecutionCallStepArguments = pydantic.Field()
    """
    Required. The arguments to pass to the code execution.
    """

    id: str = pydantic.Field()
    """
    Required. A unique ID for this specific tool call.
    """

    signature: typing.Optional[str] = pydantic.Field(default=None)
    """
    A signature hash for backend validation.
    """

    type: CodeExecutionCallStepType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
