# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .code_execution_call_step_arguments_language import CodeExecutionCallStepArgumentsLanguage


class CodeExecutionCallStepArguments(UniversalBaseModel):
    """
    The arguments to pass to the code execution.
    """

    code: typing.Optional[str] = pydantic.Field(default=None)
    """
    The code to be executed.
    """

    language: typing.Optional[CodeExecutionCallStepArgumentsLanguage] = pydantic.Field(default=None)
    """
    Programming language of the `code`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
