# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .code_execution_call_arguments import CodeExecutionCallArguments
from .code_execution_call_delta_type import CodeExecutionCallDeltaType


class CodeExecutionCallDelta(UniversalBaseModel):
    arguments: CodeExecutionCallArguments
    signature: typing.Optional[str] = pydantic.Field(default=None)
    """
    A signature hash for backend validation.
    """

    type: CodeExecutionCallDeltaType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
