# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .computer_use_environment import ComputerUseEnvironment
from .computer_use_type import ComputerUseType


class ComputerUse(UniversalBaseModel):
    """
    A tool that can be used by the model to interact with the computer.
    """

    environment: typing.Optional[ComputerUseEnvironment] = pydantic.Field(default=None)
    """
    The environment being operated.
    """

    excluded_predefined_functions: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The list of predefined functions that are excluded from the model call.
    """

    type: ComputerUseType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
