# This file was auto-generated by Fern from our API Definition.

import typing

from .audio_content import AudioContent
from .document_content import DocumentContent
from .image_content import ImageContent
from .text_content import TextContent
from .video_content import VideoContent

Content = typing.Union[TextContent, ImageContent, AudioContent, DocumentContent, VideoContent]
