# This file was auto-generated by Fern from our API Definition.

import typing

from .environment_config import EnvironmentConfig

CreateModelInteractionParamsEnvironment = typing.Union[str, EnvironmentConfig]
