# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_model_interaction_params_environment import CreateModelInteractionParamsEnvironment
from .create_model_interaction_params_response_format import CreateModelInteractionParamsResponseFormat
from .generation_config import GenerationConfig
from .interactions_input import InteractionsInput
from .model_option import ModelOption
from .response_modality import ResponseModality
from .service_tier import ServiceTier
from .tool import Tool
from .webhook_config import WebhookConfig


class CreateModelInteractionParams(UniversalBaseModel):
    """
    Parameters for creating model interactions
    """

    model: ModelOption = pydantic.Field()
    """
    The name of the `Model` used for generating the interaction.
    """

    background: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Input only. Whether to run the model interaction in the background.
    """

    store: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Input only. Whether to store the response and request for later retrieval.
    """

    stream: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Input only. Whether the interaction will be streamed.
    """

    environment: typing.Optional[CreateModelInteractionParamsEnvironment] = pydantic.Field(default=None)
    """
    The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
    """

    input: InteractionsInput
    previous_interaction_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the previous interaction, if any.
    """

    response_format: typing.Optional[CreateModelInteractionParamsResponseFormat] = pydantic.Field(default=None)
    """
    Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
    """

    response_mime_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The mime type of the response. This is required if response_format is set.
    """

    response_modalities: typing.Optional[typing.List[ResponseModality]] = pydantic.Field(default=None)
    """
    The requested modalities of the response (TEXT, IMAGE, AUDIO).
    """

    service_tier: typing.Optional[ServiceTier] = pydantic.Field(default=None)
    """
    The service tier for the interaction.
    """

    system_instruction: typing.Optional[str] = pydantic.Field(default=None)
    """
    System instruction for the interaction.
    """

    tools: typing.Optional[typing.List[Tool]] = pydantic.Field(default=None)
    """
    A list of tool declarations the model may call during interaction.
    """

    webhook_config: typing.Optional[WebhookConfig] = pydantic.Field(default=None)
    """
    Optional. Webhook configuration for receiving notifications when the
    interaction completes.
    """

    generation_config: typing.Optional[GenerationConfig] = pydantic.Field(default=None)
    """
    Input only. Configuration parameters for the model interaction.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
