# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .deep_research_agent_config_type import DeepResearchAgentConfigType
from .deep_research_agent_config_visualization import DeepResearchAgentConfigVisualization
from .thinking_summaries import ThinkingSummaries


class DeepResearchAgentConfig(UniversalBaseModel):
    """
    Configuration for the Deep Research agent.
    """

    collaborative_planning: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enables human-in-the-loop planning for the Deep Research agent. If set to
    true, the Deep Research agent will provide a research plan in its response.
    The agent will then proceed only if the user confirms the plan in the next
    turn.
    """

    thinking_summaries: typing.Optional[ThinkingSummaries] = pydantic.Field(default=None)
    """
    Whether to include thought summaries in the response.
    """

    type: DeepResearchAgentConfigType
    visualization: typing.Optional[DeepResearchAgentConfigVisualization] = pydantic.Field(default=None)
    """
    Whether to include visualizations in the response.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
