# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .document_content_mime_type import DocumentContentMimeType
from .document_content_type import DocumentContentType


class DocumentContent(UniversalBaseModel):
    """
    A document content block.
    """

    data: typing.Optional[str] = pydantic.Field(default=None)
    """
    The document content.
    """

    mime_type: typing.Optional[DocumentContentMimeType] = pydantic.Field(default=None)
    """
    The mime type of the document.
    """

    type: DocumentContentType
    uri: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URI of the document.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
