# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .environment_config_network import EnvironmentConfigNetwork
from .environment_config_type import EnvironmentConfigType
from .source import Source


class EnvironmentConfig(UniversalBaseModel):
    """
    Configuration for a custom environment.
    """

    network: typing.Optional[EnvironmentConfigNetwork] = pydantic.Field(default=None)
    """
    Network configuration for the environment.
    """

    sources: typing.Optional[typing.List[Source]] = None
    type: EnvironmentConfigType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
