# This file was auto-generated by Fern from our API Definition.

import typing

from .environment_network_egress_allowlist_allowlist import EnvironmentNetworkEgressAllowlistAllowlist
from .environment_network_egress_allowlist_one import EnvironmentNetworkEgressAllowlistOne

EnvironmentNetworkEgressAllowlist = typing.Union[
    EnvironmentNetworkEgressAllowlistAllowlist, EnvironmentNetworkEgressAllowlistOne
]
