# This file was auto-generated by Fern from our API Definition.

import typing

from .environment_config_network_one import EnvironmentConfigNetworkOne
from .environment_network_egress_allowlist import EnvironmentNetworkEgressAllowlist

EnvironmentConfigNetwork = typing.Union[EnvironmentNetworkEgressAllowlist, EnvironmentConfigNetworkOne]
