# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .error import Error
from .error_event_event_type import ErrorEventEventType


class ErrorEvent(UniversalBaseModel):
    error: typing.Optional[Error] = None
    event_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The event_id token to be used to resume the interaction stream, from
    this event.
    """

    event_type: ErrorEventEventType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
