# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .file_citation_type import FileCitationType


class FileCitation(UniversalBaseModel):
    """
    A file citation annotation.
    """

    custom_metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    User provided metadata about the retrieved context.
    """

    document_uri: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URI of the file.
    """

    end_index: typing.Optional[int] = pydantic.Field(default=None)
    """
    End of the attributed segment, exclusive.
    """

    file_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the file.
    """

    media_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Media ID in-case of image citations, if applicable.
    """

    page_number: typing.Optional[int] = pydantic.Field(default=None)
    """
    Page number of the cited document, if applicable.
    """

    source: typing.Optional[str] = pydantic.Field(default=None)
    """
    Source attributed for a portion of the text.
    """

    start_index: typing.Optional[int] = pydantic.Field(default=None)
    """
    Start of segment of the response that is attributed to this source.
    
    Index indicates the start of the segment, measured in bytes.
    """

    type: FileCitationType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
