# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .file_search_type import FileSearchType


class FileSearch(UniversalBaseModel):
    """
    A tool that can be used by the model to search files.
    """

    file_search_store_names: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The file search store names to search.
    """

    metadata_filter: typing.Optional[str] = pydantic.Field(default=None)
    """
    Metadata filter to apply to the semantic retrieval documents and chunks.
    """

    top_k: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of semantic retrieval chunks to retrieve.
    """

    type: FileSearchType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
