# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .function_type import FunctionType


class Function(UniversalBaseModel):
    """
    A tool that can be used by the model.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    A description of the function.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the function.
    """

    parameters: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    The JSON Schema for the function's parameters.
    """

    type: FunctionType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
