# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .function_call_step_type import FunctionCallStepType


class FunctionCallStep(UniversalBaseModel):
    """
    A function tool call step.
    """

    arguments: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Required. The arguments to pass to the function.
    """

    id: str = pydantic.Field()
    """
    Required. A unique ID for this specific tool call.
    """

    name: str = pydantic.Field()
    """
    Required. The name of the tool to call.
    """

    signature: typing.Optional[str] = pydantic.Field(default=None)
    """
    A signature hash for backend validation.
    """

    type: FunctionCallStepType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
