# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_config_tool_choice import GenerationConfigToolChoice
from .image_config import ImageConfig
from .speech_config import SpeechConfig
from .thinking_level import ThinkingLevel
from .thinking_summaries import ThinkingSummaries


class GenerationConfig(UniversalBaseModel):
    """
    Configuration parameters for model interactions.
    """

    image_config: typing.Optional[ImageConfig] = pydantic.Field(default=None)
    """
    Configuration for image interaction.
    """

    max_output_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    The maximum number of tokens to include in the response.
    """

    seed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seed used in decoding for reproducibility.
    """

    speech_config: typing.Optional[typing.List[SpeechConfig]] = pydantic.Field(default=None)
    """
    Configuration for speech interaction.
    """

    stop_sequences: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    A list of character sequences that will stop output interaction.
    """

    temperature: typing.Optional[float] = pydantic.Field(default=None)
    """
    Controls the randomness of the output.
    """

    thinking_level: typing.Optional[ThinkingLevel] = pydantic.Field(default=None)
    """
    The level of thought tokens that the model should generate.
    """

    thinking_summaries: typing.Optional[ThinkingSummaries] = pydantic.Field(default=None)
    """
    Whether to include thought summaries in the response.
    """

    tool_choice: typing.Optional[GenerationConfigToolChoice] = pydantic.Field(default=None)
    """
    The tool choice configuration.
    """

    top_p: typing.Optional[float] = pydantic.Field(default=None)
    """
    The maximum cumulative probability of tokens to consider when sampling.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
