# This file was auto-generated by Fern from our API Definition.

import typing

from .tool_choice_config import ToolChoiceConfig
from .tool_choice_type import ToolChoiceType

GenerationConfigToolChoice = typing.Union[ToolChoiceType, ToolChoiceConfig]
