# This file was auto-generated by Fern from our API Definition.

import typing

GoogleSearchSearchTypesItem = typing.Union[
    typing.Literal["web_search", "image_search", "enterprise_web_search"], typing.Any
]
