# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .google_maps_type import GoogleMapsType


class GoogleMaps(UniversalBaseModel):
    """
    A tool that can be used by the model to call Google Maps.
    """

    enable_widget: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to return a widget context token in the tool call result of the
    response.
    """

    latitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    The latitude of the user's location.
    """

    longitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    The longitude of the user's location.
    """

    type: GoogleMapsType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
