# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .google_search_search_types_item import GoogleSearchSearchTypesItem
from .google_search_type import GoogleSearchType


class GoogleSearch(UniversalBaseModel):
    """
    A tool that can be used by the model to search Google.
    """

    search_types: typing.Optional[typing.List[GoogleSearchSearchTypesItem]] = pydantic.Field(default=None)
    """
    The types of search grounding to enable.
    """

    type: GoogleSearchType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
