# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .google_search_call_step_arguments import GoogleSearchCallStepArguments
from .google_search_call_step_search_type import GoogleSearchCallStepSearchType
from .google_search_call_step_type import GoogleSearchCallStepType


class GoogleSearchCallStep(UniversalBaseModel):
    """
    Google Search call step.
    """

    arguments: GoogleSearchCallStepArguments = pydantic.Field()
    """
    Required. The arguments to pass to Google Search.
    """

    id: str = pydantic.Field()
    """
    Required. A unique ID for this specific tool call.
    """

    search_type: typing.Optional[GoogleSearchCallStepSearchType] = pydantic.Field(default=None)
    """
    The type of search grounding enabled.
    """

    signature: typing.Optional[str] = pydantic.Field(default=None)
    """
    A signature hash for backend validation.
    """

    type: GoogleSearchCallStepType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
