# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .image_config_aspect_ratio import ImageConfigAspectRatio
from .image_config_image_size import ImageConfigImageSize


class ImageConfig(UniversalBaseModel):
    """
    The configuration for image interaction.
    """

    aspect_ratio: typing.Optional[ImageConfigAspectRatio] = None
    image_size: typing.Optional[ImageConfigImageSize] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
