# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .image_content_mime_type import ImageContentMimeType
from .image_content_type import ImageContentType
from .media_resolution import MediaResolution


class ImageContent(UniversalBaseModel):
    """
    An image content block.
    """

    data: typing.Optional[str] = pydantic.Field(default=None)
    """
    The image content.
    """

    mime_type: typing.Optional[ImageContentMimeType] = pydantic.Field(default=None)
    """
    The mime type of the image.
    """

    resolution: typing.Optional[MediaResolution] = pydantic.Field(default=None)
    """
    The resolution of the media.
    """

    type: ImageContentType
    uri: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URI of the image.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
