# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .image_response_format_aspect_ratio import ImageResponseFormatAspectRatio
from .image_response_format_delivery import ImageResponseFormatDelivery
from .image_response_format_image_size import ImageResponseFormatImageSize
from .image_response_format_mime_type import ImageResponseFormatMimeType
from .image_response_format_type import ImageResponseFormatType


class ImageResponseFormat(UniversalBaseModel):
    """
    Configuration for image output format.
    """

    aspect_ratio: typing.Optional[ImageResponseFormatAspectRatio] = pydantic.Field(default=None)
    """
    The aspect ratio for the image output.
    """

    delivery: typing.Optional[ImageResponseFormatDelivery] = pydantic.Field(default=None)
    """
    The delivery mode for the image output.
    """

    image_size: typing.Optional[ImageResponseFormatImageSize] = pydantic.Field(default=None)
    """
    The size of the image output.
    """

    mime_type: typing.Optional[ImageResponseFormatMimeType] = pydantic.Field(default=None)
    """
    The MIME type of the image output.
    """

    type: ImageResponseFormatType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
