# This file was auto-generated by Fern from our API Definition.

import typing

ImageContentMimeType = typing.Union[
    typing.Literal[
        "image/png", "image/jpeg", "image/webp", "image/heic", "image/heif", "image/gif", "image/bmp", "image/tiff"
    ],
    typing.Any,
]
