# This file was auto-generated by Fern from our API Definition.

import typing

ImageResponseFormatAspectRatio = typing.Union[
    typing.Literal["1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9", "21:9", "1:8", "8:1", "1:4", "4:1"],
    typing.Any,
]
