# This file was auto-generated by Fern from our API Definition.

import typing

from .error_event import ErrorEvent
from .interaction_completed_event import InteractionCompletedEvent
from .interaction_created_event import InteractionCreatedEvent
from .interaction_status_update import InteractionStatusUpdate
from .step_delta import StepDelta
from .step_start import StepStart
from .step_stop import StepStop

InteractionSseEvent = typing.Union[
    InteractionCreatedEvent,
    InteractionCompletedEvent,
    InteractionStatusUpdate,
    ErrorEvent,
    StepStart,
    StepDelta,
    StepStop,
]
