# This file was auto-generated by Fern from our API Definition.

import typing

from .content import Content
from .step import Step

InteractionsInput = typing.Union[str, typing.List[Step], typing.List[Content], Content]
