# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_option import AgentOption
from .generation_config import GenerationConfig
from .interaction_agent_config import InteractionAgentConfig
from .interaction_environment import InteractionEnvironment
from .interaction_response_format import InteractionResponseFormat
from .interaction_status import InteractionStatus
from .interactions_input import InteractionsInput
from .model_option import ModelOption
from .response_modality import ResponseModality
from .service_tier import ServiceTier
from .step import Step
from .tool import Tool
from .usage import Usage
from .webhook_config import WebhookConfig


class Interaction(UniversalBaseModel):
    """
    The Interaction resource.
    """

    model: typing.Optional[ModelOption] = pydantic.Field(default=None)
    """
    The name of the `Model` used for generating the interaction.
    """

    agent: typing.Optional[AgentOption] = pydantic.Field(default=None)
    """
    The name of the `Agent` used for generating the interaction.
    """

    created: dt.datetime = pydantic.Field()
    """
    Required. Output only. The time at which the response was created in ISO 8601 format
    (YYYY-MM-DDThh:mm:ssZ).
    """

    environment: typing.Optional[InteractionEnvironment] = pydantic.Field(default=None)
    """
    The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
    """

    environment_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Output only. The environment ID for the interaction. Only populated if environment
    config is set in the request.
    """

    id: str = pydantic.Field()
    """
    Required. Output only. A unique identifier for the interaction completion.
    """

    input: typing.Optional[InteractionsInput] = None
    previous_interaction_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the previous interaction, if any.
    """

    response_format: typing.Optional[InteractionResponseFormat] = pydantic.Field(default=None)
    """
    Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
    """

    response_mime_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The mime type of the response. This is required if response_format is set.
    """

    response_modalities: typing.Optional[typing.List[ResponseModality]] = pydantic.Field(default=None)
    """
    The requested modalities of the response (TEXT, IMAGE, AUDIO).
    """

    role: typing.Optional[str] = pydantic.Field(default=None)
    """
    Output only. The role of the interaction.
    """

    service_tier: typing.Optional[ServiceTier] = pydantic.Field(default=None)
    """
    The service tier for the interaction.
    """

    status: InteractionStatus = pydantic.Field()
    """
    Required. Output only. The status of the interaction.
    """

    steps: typing.Optional[typing.List[Step]] = pydantic.Field(default=None)
    """
    Required. Output only. The steps that make up the interaction.
    """

    system_instruction: typing.Optional[str] = pydantic.Field(default=None)
    """
    System instruction for the interaction.
    """

    tools: typing.Optional[typing.List[Tool]] = pydantic.Field(default=None)
    """
    A list of tool declarations the model may call during interaction.
    """

    updated: dt.datetime = pydantic.Field()
    """
    Required. Output only. The time at which the response was last updated in ISO 8601 format
    (YYYY-MM-DDThh:mm:ssZ).
    """

    usage: typing.Optional[Usage] = pydantic.Field(default=None)
    """
    Output only. Statistics on the interaction request's token usage.
    """

    webhook_config: typing.Optional[WebhookConfig] = pydantic.Field(default=None)
    """
    Optional. Webhook configuration for receiving notifications when the
    interaction completes.
    """

    generation_config: typing.Optional[GenerationConfig] = pydantic.Field(default=None)
    """
    Input only. Configuration parameters for the model interaction.
    """

    agent_config: typing.Optional[InteractionAgentConfig] = pydantic.Field(default=None)
    """
    Configuration parameters for the agent interaction.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
