# This file was auto-generated by Fern from our API Definition.

import typing

InteractionStatusUpdateStatus = typing.Union[
    typing.Literal["in_progress", "requires_action", "completed", "failed", "cancelled", "incomplete"], typing.Any
]
