# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .interaction_status_update_event_type import InteractionStatusUpdateEventType
from .interaction_status_update_status import InteractionStatusUpdateStatus


class InteractionStatusUpdate(UniversalBaseModel):
    event_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The event_id token to be used to resume the interaction stream, from
    this event.
    """

    event_type: InteractionStatusUpdateEventType
    interaction_id: str
    status: InteractionStatusUpdateStatus

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
