# This file was auto-generated by Fern from our API Definition.

import typing

from .response_format import ResponseFormat
from .response_format_list import ResponseFormatList

InteractionResponseFormat = typing.Union[ResponseFormatList, ResponseFormat]
