# This file was auto-generated by Fern from our API Definition.

import typing

from .deep_research_agent_config import DeepResearchAgentConfig
from .dynamic_agent_config import DynamicAgentConfig

InteractionAgentConfig = typing.Union[DynamicAgentConfig, DeepResearchAgentConfig]
