# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_read import WebhookRead


class ListWebhooksResponse(UniversalBaseModel):
    """
    Response message for WebhookService.ListWebhooks.
    """

    next_page_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    A token, which can be sent as `page_token` to retrieve the next page.
    If this field is omitted, there are no subsequent pages.
    """

    webhooks: typing.Optional[typing.List[WebhookRead]] = pydantic.Field(default=None)
    """
    The webhooks.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
