# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .allowed_tools import AllowedTools
from .mcp_server_type import McpServerType


class McpServer(UniversalBaseModel):
    """
    A MCPServer is a server that can be called by the model to perform actions.
    """

    allowed_tools: typing.Optional[typing.List[AllowedTools]] = pydantic.Field(default=None)
    """
    The allowed tools.
    """

    headers: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Optional: Fields for authentication headers, timeouts, etc., if needed.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the MCPServer.
    """

    type: McpServerType
    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The full URL for the MCPServer endpoint.
    Example: "https://api.example.com/mcp"
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
