# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .mcp_server_tool_call_step_type import McpServerToolCallStepType


class McpServerToolCallStep(UniversalBaseModel):
    """
    MCPServer tool call step.
    """

    arguments: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Required. The JSON object of arguments for the function.
    """

    id: str = pydantic.Field()
    """
    Required. A unique ID for this specific tool call.
    """

    name: str = pydantic.Field()
    """
    Required. The name of the tool which was called.
    """

    server_name: str = pydantic.Field()
    """
    Required. The name of the used MCP server.
    """

    signature: typing.Optional[str] = pydantic.Field(default=None)
    """
    A signature hash for backend validation.
    """

    type: McpServerToolCallStepType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
