# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .mcp_server_tool_call_delta_type import McpServerToolCallDeltaType


class McpServerToolCallDelta(UniversalBaseModel):
    arguments: typing.Dict[str, typing.Any]
    name: str
    server_name: str
    signature: typing.Optional[str] = pydantic.Field(default=None)
    """
    A signature hash for backend validation.
    """

    type: McpServerToolCallDeltaType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
