# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .response_modality import ResponseModality


class ModalityTokens(UniversalBaseModel):
    """
    The token count for a single response modality.
    """

    modality: typing.Optional[ResponseModality] = pydantic.Field(default=None)
    """
    The modality associated with the token count.
    """

    tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of tokens for the modality.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
