# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .content import Content
from .model_output_step_type import ModelOutputStepType


class ModelOutputStep(UniversalBaseModel):
    """
    Output generated by the model.
    """

    content: typing.Optional[typing.List[Content]] = None
    type: ModelOutputStepType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
