# This file was auto-generated by Fern from our API Definition.

import typing

from .model_option_eight import ModelOptionEight
from .model_option_eighteen import ModelOptionEighteen
from .model_option_eleven import ModelOptionEleven
from .model_option_fifteen import ModelOptionFifteen
from .model_option_five import ModelOptionFive
from .model_option_four import ModelOptionFour
from .model_option_fourteen import ModelOptionFourteen
from .model_option_nine import ModelOptionNine
from .model_option_nineteen import ModelOptionNineteen
from .model_option_one import ModelOptionOne
from .model_option_seven import ModelOptionSeven
from .model_option_seventeen import ModelOptionSeventeen
from .model_option_six import ModelOptionSix
from .model_option_sixteen import ModelOptionSixteen
from .model_option_ten import ModelOptionTen
from .model_option_thirteen import ModelOptionThirteen
from .model_option_three import ModelOptionThree
from .model_option_twelve import ModelOptionTwelve
from .model_option_twenty import ModelOptionTwenty
from .model_option_two import ModelOptionTwo

ModelOption = typing.Union[
    str,
    ModelOptionOne,
    ModelOptionTwo,
    ModelOptionThree,
    ModelOptionFour,
    ModelOptionFive,
    ModelOptionSix,
    ModelOptionSeven,
    ModelOptionEight,
    ModelOptionNine,
    ModelOptionTen,
    ModelOptionEleven,
    ModelOptionTwelve,
    ModelOptionThirteen,
    ModelOptionFourteen,
    ModelOptionFifteen,
    ModelOptionSixteen,
    ModelOptionSeventeen,
    ModelOptionEighteen,
    ModelOptionNineteen,
    ModelOptionTwenty,
]
