# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .place_citation_type import PlaceCitationType
from .review_snippet import ReviewSnippet


class PlaceCitation(UniversalBaseModel):
    """
    A place citation annotation.
    """

    end_index: typing.Optional[int] = pydantic.Field(default=None)
    """
    End of the attributed segment, exclusive.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Title of the place.
    """

    place_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the place, in `places/{place_id}` format.
    """

    review_snippets: typing.Optional[typing.List[ReviewSnippet]] = pydantic.Field(default=None)
    """
    Snippets of reviews that are used to generate answers about the
    features of a given place in Google Maps.
    """

    start_index: typing.Optional[int] = pydantic.Field(default=None)
    """
    Start of segment of the response that is attributed to this source.
    
    Index indicates the start of the segment, measured in bytes.
    """

    type: PlaceCitationType
    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URI reference of the place.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
