# This file was auto-generated by Fern from our API Definition.

import typing

from .audio_response_format import AudioResponseFormat
from .image_response_format import ImageResponseFormat
from .text_response_format import TextResponseFormat

ResponseFormat = typing.Union[
    AudioResponseFormat, TextResponseFormat, ImageResponseFormat, typing.Dict[str, typing.Any]
]
