# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .retrieval_retrieval_types_item import RetrievalRetrievalTypesItem
from .retrieval_type import RetrievalType
from .vertex_ai_search_config import VertexAiSearchConfig


class Retrieval(UniversalBaseModel):
    """
    A tool that can be used by the model to retrieve files.
    """

    retrieval_types: typing.Optional[typing.List[RetrievalRetrievalTypesItem]] = pydantic.Field(default=None)
    """
    The types of file retrieval to enable.
    """

    type: RetrievalType
    vertex_ai_search_config: typing.Optional[VertexAiSearchConfig] = pydantic.Field(default=None)
    """
    Used to specify configuration for VertexAISearch.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
