# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ReviewSnippet(UniversalBaseModel):
    """
    Encapsulates a snippet of a user review that answers a question about
    the features of a specific place in Google Maps.
    """

    review_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the review snippet.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Title of the review.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    A link that corresponds to the user review on Google Maps.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
