# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SigningSecretRead(UniversalBaseModel):
    """
    Represents a signing secret used to verify webhook payloads.
    """

    expire_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Output only. The expiration date of the signing secret.
    """

    truncated_secret: typing.Optional[str] = pydantic.Field(default=None)
    """
    Output only. The truncated version of the signing secret.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
