# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .source_type import SourceType


class Source(UniversalBaseModel):
    """
    A source to be mounted into the environment.
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    The inline content if `type` is `INLINE`.
    """

    encoding: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional encoding for inline content (e.g. `base64`).
    """

    source: typing.Optional[str] = pydantic.Field(default=None)
    """
    The source of the environment.
    For GCS, this is the GCS path.
    For GitHub, this is the GitHub path.
    """

    target: typing.Optional[str] = pydantic.Field(default=None)
    """
    Where the source should appear in the environment.
    """

    type: typing.Optional[SourceType] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
