# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SpeechConfig(UniversalBaseModel):
    """
    The configuration for speech interaction.
    """

    language: typing.Optional[str] = pydantic.Field(default=None)
    """
    The language of the speech.
    """

    speaker: typing.Optional[str] = pydantic.Field(default=None)
    """
    The speaker's name, it should match the speaker name given in the prompt.
    """

    voice: typing.Optional[str] = pydantic.Field(default=None)
    """
    The voice of the speaker.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
