# This file was auto-generated by Fern from our API Definition.

import typing

from .code_execution_call_step import CodeExecutionCallStep
from .code_execution_result_step import CodeExecutionResultStep
from .file_search_call_step import FileSearchCallStep
from .file_search_result_step import FileSearchResultStep
from .function_call_step import FunctionCallStep
from .function_result_step import FunctionResultStep
from .google_maps_call_step import GoogleMapsCallStep
from .google_maps_result_step import GoogleMapsResultStep
from .google_search_call_step import GoogleSearchCallStep
from .google_search_result_step import GoogleSearchResultStep
from .mcp_server_tool_call_step import McpServerToolCallStep
from .mcp_server_tool_result_step import McpServerToolResultStep
from .model_output_step import ModelOutputStep
from .thought_step import ThoughtStep
from .url_context_call_step import UrlContextCallStep
from .url_context_result_step import UrlContextResultStep
from .user_input_step import UserInputStep

Step = typing.Union[
    UserInputStep,
    ModelOutputStep,
    ThoughtStep,
    FunctionCallStep,
    CodeExecutionCallStep,
    UrlContextCallStep,
    McpServerToolCallStep,
    GoogleSearchCallStep,
    FileSearchCallStep,
    GoogleMapsCallStep,
    FunctionResultStep,
    CodeExecutionResultStep,
    UrlContextResultStep,
    GoogleSearchResultStep,
    McpServerToolResultStep,
    FileSearchResultStep,
    GoogleMapsResultStep,
]
