# This file was auto-generated by Fern from our API Definition.

import typing

from .arguments_delta import ArgumentsDelta
from .audio_delta import AudioDelta
from .code_execution_call_delta import CodeExecutionCallDelta
from .code_execution_result_delta import CodeExecutionResultDelta
from .document_delta import DocumentDelta
from .file_search_call_delta import FileSearchCallDelta
from .file_search_result_delta import FileSearchResultDelta
from .function_result_delta import FunctionResultDelta
from .google_maps_call_delta import GoogleMapsCallDelta
from .google_maps_result_delta import GoogleMapsResultDelta
from .google_search_call_delta import GoogleSearchCallDelta
from .google_search_result_delta import GoogleSearchResultDelta
from .image_delta import ImageDelta
from .mcp_server_tool_call_delta import McpServerToolCallDelta
from .mcp_server_tool_result_delta import McpServerToolResultDelta
from .text_annotation_delta import TextAnnotationDelta
from .text_delta import TextDelta
from .thought_signature_delta import ThoughtSignatureDelta
from .thought_summary_delta import ThoughtSummaryDelta
from .url_context_call_delta import UrlContextCallDelta
from .url_context_result_delta import UrlContextResultDelta
from .video_delta import VideoDelta

StepDeltaData = typing.Union[
    TextDelta,
    ImageDelta,
    AudioDelta,
    DocumentDelta,
    VideoDelta,
    ThoughtSummaryDelta,
    ThoughtSignatureDelta,
    TextAnnotationDelta,
    ArgumentsDelta,
    CodeExecutionCallDelta,
    UrlContextCallDelta,
    GoogleSearchCallDelta,
    McpServerToolCallDelta,
    FileSearchCallDelta,
    GoogleMapsCallDelta,
    CodeExecutionResultDelta,
    UrlContextResultDelta,
    GoogleSearchResultDelta,
    McpServerToolResultDelta,
    FileSearchResultDelta,
    GoogleMapsResultDelta,
    FunctionResultDelta,
]
