# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .annotation import Annotation
from .text_annotation_delta_type import TextAnnotationDeltaType


class TextAnnotationDelta(UniversalBaseModel):
    annotations: typing.Optional[typing.List[Annotation]] = pydantic.Field(default=None)
    """
    Citation information for model-generated content.
    """

    type: TextAnnotationDeltaType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
