# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .annotation import Annotation
from .text_content_type import TextContentType


class TextContent(UniversalBaseModel):
    """
    A text content block.
    """

    annotations: typing.Optional[typing.List[Annotation]] = pydantic.Field(default=None)
    """
    Citation information for model-generated content.
    """

    text: str = pydantic.Field()
    """
    Required. The text content.
    """

    type: TextContentType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
