# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .text_response_format_mime_type import TextResponseFormatMimeType
from .text_response_format_type import TextResponseFormatType


class TextResponseFormat(UniversalBaseModel):
    """
    Configuration for text output format.
    """

    mime_type: typing.Optional[TextResponseFormatMimeType] = pydantic.Field(default=None)
    """
    The MIME type of the text output.
    """

    schema_: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="schema"),
        pydantic.Field(
            alias="schema",
            description="The JSON schema that the output should conform to. Only applicable when\nmime_type is application/json.",
        ),
    ] = None
    type: TextResponseFormatType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
