# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .thought_step_type import ThoughtStepType
from .thought_summary_content import ThoughtSummaryContent


class ThoughtStep(UniversalBaseModel):
    """
    A thought step.
    """

    signature: typing.Optional[str] = pydantic.Field(default=None)
    """
    A signature hash for backend validation.
    """

    summary: typing.Optional[typing.List[ThoughtSummaryContent]] = pydantic.Field(default=None)
    """
    A summary of the thought.
    """

    type: ThoughtStepType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
