# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .thought_summary_content import ThoughtSummaryContent
from .thought_summary_delta_type import ThoughtSummaryDeltaType


class ThoughtSummaryDelta(UniversalBaseModel):
    content: typing.Optional[ThoughtSummaryContent] = pydantic.Field(default=None)
    """
    A new summary item to be added to the thought.
    """

    type: ThoughtSummaryDeltaType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
