# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .thought_signature_delta_type import ThoughtSignatureDeltaType


class ThoughtSignatureDelta(UniversalBaseModel):
    signature: typing.Optional[str] = pydantic.Field(default=None)
    """
    Signature to match the backend source to be part of the generation.
    """

    type: ThoughtSignatureDeltaType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
