# This file was auto-generated by Fern from our API Definition.

import typing

from .code_execution import CodeExecution
from .computer_use import ComputerUse
from .file_search import FileSearch
from .function import Function
from .google_maps import GoogleMaps
from .google_search import GoogleSearch
from .mcp_server import McpServer
from .retrieval import Retrieval
from .url_context import UrlContext

Tool = typing.Union[
    Function, CodeExecution, UrlContext, ComputerUse, McpServer, GoogleSearch, FileSearch, GoogleMaps, Retrieval
]
