# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .allowed_tools import AllowedTools


class ToolChoiceConfig(UniversalBaseModel):
    """
    The tool choice configuration containing allowed tools.
    """

    allowed_tools: typing.Optional[AllowedTools] = pydantic.Field(default=None)
    """
    The allowed tools.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
