# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .turn_content import TurnContent


class Turn(UniversalBaseModel):
    content: typing.Optional[TurnContent] = None
    role: typing.Optional[str] = pydantic.Field(default=None)
    """
    The originator of this turn. Must be user for input or model for
    model output.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
