# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .url_citation_type import UrlCitationType


class UrlCitation(UniversalBaseModel):
    """
    A URL citation annotation.
    """

    end_index: typing.Optional[int] = pydantic.Field(default=None)
    """
    End of the attributed segment, exclusive.
    """

    start_index: typing.Optional[int] = pydantic.Field(default=None)
    """
    Start of segment of the response that is attributed to this source.
    
    Index indicates the start of the segment, measured in bytes.
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    The title of the URL.
    """

    type: UrlCitationType
    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
