# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .grounding_tool_count import GroundingToolCount
from .modality_tokens import ModalityTokens


class Usage(UniversalBaseModel):
    """
    Statistics on the interaction request's token usage.
    """

    cached_tokens_by_modality: typing.Optional[typing.List[ModalityTokens]] = pydantic.Field(default=None)
    """
    A breakdown of cached token usage by modality.
    """

    grounding_tool_count: typing.Optional[typing.List[GroundingToolCount]] = pydantic.Field(default=None)
    """
    Grounding tool count.
    """

    input_tokens_by_modality: typing.Optional[typing.List[ModalityTokens]] = pydantic.Field(default=None)
    """
    A breakdown of input token usage by modality.
    """

    output_tokens_by_modality: typing.Optional[typing.List[ModalityTokens]] = pydantic.Field(default=None)
    """
    A breakdown of output token usage by modality.
    """

    tool_use_tokens_by_modality: typing.Optional[typing.List[ModalityTokens]] = pydantic.Field(default=None)
    """
    A breakdown of tool-use token usage by modality.
    """

    total_cached_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of tokens in the cached part of the prompt (the cached content).
    """

    total_input_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of tokens in the prompt (context).
    """

    total_output_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of tokens across all the generated responses.
    """

    total_thought_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of tokens of thoughts for thinking models.
    """

    total_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total token count for the interaction request (prompt + responses + other
    internal tokens).
    """

    total_tool_use_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of tokens present in tool-use prompt(s).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
