# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .media_resolution import MediaResolution
from .video_content_mime_type import VideoContentMimeType
from .video_content_type import VideoContentType


class VideoContent(UniversalBaseModel):
    """
    A video content block.
    """

    data: typing.Optional[str] = pydantic.Field(default=None)
    """
    The video content.
    """

    mime_type: typing.Optional[VideoContentMimeType] = pydantic.Field(default=None)
    """
    The mime type of the video.
    """

    resolution: typing.Optional[MediaResolution] = pydantic.Field(default=None)
    """
    The resolution of the media.
    """

    type: VideoContentType
    uri: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URI of the video.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
