# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .media_resolution import MediaResolution
from .video_delta_mime_type import VideoDeltaMimeType
from .video_delta_type import VideoDeltaType


class VideoDelta(UniversalBaseModel):
    data: typing.Optional[str] = None
    mime_type: typing.Optional[VideoDeltaMimeType] = None
    resolution: typing.Optional[MediaResolution] = pydantic.Field(default=None)
    """
    The resolution of the media.
    """

    type: VideoDeltaType
    uri: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
