# This file was auto-generated by Fern from our API Definition.

import typing

VideoDeltaMimeType = typing.Union[
    typing.Literal[
        "video/mp4",
        "video/mpeg",
        "video/mpg",
        "video/mov",
        "video/avi",
        "video/x-flv",
        "video/webm",
        "video/wmv",
        "video/3gpp",
    ],
    typing.Any,
]
