# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .signing_secret_read import SigningSecretRead
from .webhook_state import WebhookState
from .webhook_subscribed_events_item import WebhookSubscribedEventsItem


class WebhookRead(UniversalBaseModel):
    """
    A Webhook resource.
    """

    create_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Output only. The timestamp when the webhook was created.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Output only. The ID of the webhook.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional. The user-provided name of the webhook.
    """

    new_signing_secret: typing.Optional[str] = pydantic.Field(default=None)
    """
    Output only. The new signing secret for the webhook. Only populated on create.
    """

    signing_secrets: typing.Optional[typing.List[SigningSecretRead]] = pydantic.Field(default=None)
    """
    Output only. The signing secrets associated with this webhook.
    """

    state: typing.Optional[WebhookState] = pydantic.Field(default=None)
    """
    Output only. The state of the webhook.
    """

    subscribed_events: typing.List[WebhookSubscribedEventsItem] = pydantic.Field()
    """
    Required. The events that the webhook is subscribed to.
    Available events:
    - batch.succeeded
    - batch.expired
    - batch.failed
    - interaction.requires_action
    - interaction.completed
    - interaction.failed
    - video.generated
    """

    update_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Output only. The timestamp when the webhook was last updated.
    """

    uri: str = pydantic.Field()
    """
    Required. The URI to which webhook events will be sent.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
