# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebhookConfig(UniversalBaseModel):
    """
    Message for configuring webhook events for a request.
    """

    uris: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Optional. If set, these webhook URIs will be used for webhook events instead of the
    registered webhooks.
    """

    user_metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Optional. The user metadata that will be returned on each event emission to the
    webhooks.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
