# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_subscribed_events_item import WebhookSubscribedEventsItem


class Webhook(UniversalBaseModel):
    """
    A Webhook resource.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional. The user-provided name of the webhook.
    """

    subscribed_events: typing.List[WebhookSubscribedEventsItem] = pydantic.Field()
    """
    Required. The events that the webhook is subscribed to.
    Available events:
    - batch.succeeded
    - batch.expired
    - batch.failed
    - interaction.requires_action
    - interaction.completed
    - interaction.failed
    - video.generated
    """

    uri: str = pydantic.Field()
    """
    Required. The URI to which webhook events will be sent.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
