# This file was auto-generated by Fern from our API Definition.

import typing

from .webhook_subscribed_events_item_five import WebhookSubscribedEventsItemFive
from .webhook_subscribed_events_item_four import WebhookSubscribedEventsItemFour
from .webhook_subscribed_events_item_one import WebhookSubscribedEventsItemOne
from .webhook_subscribed_events_item_seven import WebhookSubscribedEventsItemSeven
from .webhook_subscribed_events_item_six import WebhookSubscribedEventsItemSix
from .webhook_subscribed_events_item_three import WebhookSubscribedEventsItemThree
from .webhook_subscribed_events_item_two import WebhookSubscribedEventsItemTwo

WebhookSubscribedEventsItem = typing.Union[
    str,
    WebhookSubscribedEventsItemOne,
    WebhookSubscribedEventsItemTwo,
    WebhookSubscribedEventsItemThree,
    WebhookSubscribedEventsItemFour,
    WebhookSubscribedEventsItemFive,
    WebhookSubscribedEventsItemSix,
    WebhookSubscribedEventsItemSeven,
]
