# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .rotate_signing_secret_request_revocation_behavior import RotateSigningSecretRequestRevocationBehavior
    from .webhook_update_state import WebhookUpdateState
    from .webhook_update_subscribed_events_item import WebhookUpdateSubscribedEventsItem
    from .webhook_update_subscribed_events_item_five import WebhookUpdateSubscribedEventsItemFive
    from .webhook_update_subscribed_events_item_four import WebhookUpdateSubscribedEventsItemFour
    from .webhook_update_subscribed_events_item_one import WebhookUpdateSubscribedEventsItemOne
    from .webhook_update_subscribed_events_item_seven import WebhookUpdateSubscribedEventsItemSeven
    from .webhook_update_subscribed_events_item_six import WebhookUpdateSubscribedEventsItemSix
    from .webhook_update_subscribed_events_item_three import WebhookUpdateSubscribedEventsItemThree
    from .webhook_update_subscribed_events_item_two import WebhookUpdateSubscribedEventsItemTwo
_dynamic_imports: typing.Dict[str, str] = {
    "RotateSigningSecretRequestRevocationBehavior": ".rotate_signing_secret_request_revocation_behavior",
    "WebhookUpdateState": ".webhook_update_state",
    "WebhookUpdateSubscribedEventsItem": ".webhook_update_subscribed_events_item",
    "WebhookUpdateSubscribedEventsItemFive": ".webhook_update_subscribed_events_item_five",
    "WebhookUpdateSubscribedEventsItemFour": ".webhook_update_subscribed_events_item_four",
    "WebhookUpdateSubscribedEventsItemOne": ".webhook_update_subscribed_events_item_one",
    "WebhookUpdateSubscribedEventsItemSeven": ".webhook_update_subscribed_events_item_seven",
    "WebhookUpdateSubscribedEventsItemSix": ".webhook_update_subscribed_events_item_six",
    "WebhookUpdateSubscribedEventsItemThree": ".webhook_update_subscribed_events_item_three",
    "WebhookUpdateSubscribedEventsItemTwo": ".webhook_update_subscribed_events_item_two",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "RotateSigningSecretRequestRevocationBehavior",
    "WebhookUpdateState",
    "WebhookUpdateSubscribedEventsItem",
    "WebhookUpdateSubscribedEventsItemFive",
    "WebhookUpdateSubscribedEventsItemFour",
    "WebhookUpdateSubscribedEventsItemOne",
    "WebhookUpdateSubscribedEventsItemSeven",
    "WebhookUpdateSubscribedEventsItemSix",
    "WebhookUpdateSubscribedEventsItemThree",
    "WebhookUpdateSubscribedEventsItemTwo",
]
