# This file was auto-generated by Fern from our API Definition.

import typing

RotateSigningSecretRequestRevocationBehavior = typing.Union[
    typing.Literal["revoke_previous_secrets_after_h24", "revoke_previous_secrets_immediately"], typing.Any
]
