# This file was auto-generated by Fern from our API Definition.

import typing

from .webhook_update_subscribed_events_item_five import WebhookUpdateSubscribedEventsItemFive
from .webhook_update_subscribed_events_item_four import WebhookUpdateSubscribedEventsItemFour
from .webhook_update_subscribed_events_item_one import WebhookUpdateSubscribedEventsItemOne
from .webhook_update_subscribed_events_item_seven import WebhookUpdateSubscribedEventsItemSeven
from .webhook_update_subscribed_events_item_six import WebhookUpdateSubscribedEventsItemSix
from .webhook_update_subscribed_events_item_three import WebhookUpdateSubscribedEventsItemThree
from .webhook_update_subscribed_events_item_two import WebhookUpdateSubscribedEventsItemTwo

WebhookUpdateSubscribedEventsItem = typing.Union[
    str,
    WebhookUpdateSubscribedEventsItemOne,
    WebhookUpdateSubscribedEventsItemTwo,
    WebhookUpdateSubscribedEventsItemThree,
    WebhookUpdateSubscribedEventsItemFour,
    WebhookUpdateSubscribedEventsItemFive,
    WebhookUpdateSubscribedEventsItemSix,
    WebhookUpdateSubscribedEventsItemSeven,
]
