# This file was auto-generated by Fern from our API Definition.

import typing

WebhookUpdateState = typing.Union[
    typing.Literal["enabled", "disabled", "disabled_due_to_failed_deliveries"], typing.Any
]
