# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.create_agent_interaction_params import CreateAgentInteractionParams
from ...types.create_model_interaction_params import CreateModelInteractionParams

CreateFernInteractionsStreamRequest = typing.Union[CreateModelInteractionParams, CreateAgentInteractionParams]
